package com.jez.modules.admin.system.mapper;

import com.jez.modules.admin.system.entity.GroupResource;
import com.jez.modules.admin.system.example.GroupResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupResourceMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  long countByExample(GroupResourceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int deleteByExample(GroupResourceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int deleteByPrimaryKey(@Param("groupId") Long groupId, @Param("resourceId") Long resourceId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int insert(GroupResource record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int insertSelective(GroupResource record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  List<GroupResource> selectByExample(GroupResourceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int updateByExampleSelective(@Param("record") GroupResource record,
      @Param("example") GroupResourceExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_resource
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int updateByExample(@Param("record") GroupResource record,
      @Param("example") GroupResourceExample example);
}