package com.jez.modules.admin.system.mapper;

import com.jez.modules.admin.system.entity.GroupUser;
import com.jez.modules.admin.system.example.GroupUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupUserMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  long countByExample(GroupUserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int deleteByExample(GroupUserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int deleteByPrimaryKey(@Param("groupId") Long groupId, @Param("userId") Long userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int insert(GroupUser record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int insertSelective(GroupUser record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  List<GroupUser> selectByExample(GroupUserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int updateByExampleSelective(@Param("record") GroupUser record,
      @Param("example") GroupUserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group_user
   *
   * @mbg.generated Sun Jul 09 20:29:29 CST 2017
   */
  int updateByExample(@Param("record") GroupUser record,
      @Param("example") GroupUserExample example);
}