package com.jez.modules.admin.system.mapper;

import com.jez.data.mybatis.mapper.CrudMapper;
import com.jez.modules.admin.system.entity.LoginLog;
import com.jez.modules.admin.system.example.LoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginLogMapper extends CrudMapper<Long, LoginLog, LoginLogExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_login_log
   *
   * @mbg.generated Mon Jul 17 18:09:01 CST 2017
   */
  List<LoginLog> selectByExampleWithBLOBs(LoginLogExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_login_log
   *
   * @mbg.generated Mon Jul 17 18:09:01 CST 2017
   */
  int updateByExampleWithBLOBs(@Param("record") LoginLog record,
      @Param("example") LoginLogExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_login_log
   *
   * @mbg.generated Mon Jul 17 18:09:01 CST 2017
   */
  int updateByPrimaryKeyWithBLOBs(LoginLog record);

}