package com.jez.modules.admin.system.mapper;

import com.jez.data.mybatis.mapper.CrudMapper;
import com.jez.modules.admin.system.entity.OperationLog;
import com.jez.modules.admin.system.example.OperationLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OperationLogMapper extends CrudMapper<Long, OperationLog, OperationLogExample> {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Mon Jul 17 18:09:01 CST 2017
   */
  List<OperationLog> selectByExampleWithBLOBs(OperationLogExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Mon Jul 17 18:09:01 CST 2017
   */
  int updateByExampleWithBLOBs(@Param("record") OperationLog record,
      @Param("example") OperationLogExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Mon Jul 17 18:09:01 CST 2017
   */
  int updateByPrimaryKeyWithBLOBs(OperationLog record);

}