package com.jez.modules.admin.system.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DictExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public DictExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("d.id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("d.id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("d.id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("d.id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("d.id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("d.id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("d.id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("d.id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("d.id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("d.id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("d.id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("d.id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNull() {
      addCriterion("d.created_by is null");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNotNull() {
      addCriterion("d.created_by is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedByEqualTo(Long value) {
      addCriterion("d.created_by =", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotEqualTo(Long value) {
      addCriterion("d.created_by <>", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThan(Long value) {
      addCriterion("d.created_by >", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
      addCriterion("d.created_by >=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThan(Long value) {
      addCriterion("d.created_by <", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThanOrEqualTo(Long value) {
      addCriterion("d.created_by <=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByIn(List<Long> values) {
      addCriterion("d.created_by in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotIn(List<Long> values) {
      addCriterion("d.created_by not in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByBetween(Long value1, Long value2) {
      addCriterion("d.created_by between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotBetween(Long value1, Long value2) {
      addCriterion("d.created_by not between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNull() {
      addCriterion("d.created_date is null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNotNull() {
      addCriterion("d.created_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateEqualTo(Date value) {
      addCriterion("d.created_date =", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotEqualTo(Date value) {
      addCriterion("d.created_date <>", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThan(Date value) {
      addCriterion("d.created_date >", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("d.created_date >=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThan(Date value) {
      addCriterion("d.created_date <", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
      addCriterion("d.created_date <=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIn(List<Date> values) {
      addCriterion("d.created_date in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotIn(List<Date> values) {
      addCriterion("d.created_date not in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateBetween(Date value1, Date value2) {
      addCriterion("d.created_date between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
      addCriterion("d.created_date not between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNull() {
      addCriterion("d.last_modified_by is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNotNull() {
      addCriterion("d.last_modified_by is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByEqualTo(Long value) {
      addCriterion("d.last_modified_by =", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotEqualTo(Long value) {
      addCriterion("d.last_modified_by <>", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThan(Long value) {
      addCriterion("d.last_modified_by >", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThanOrEqualTo(Long value) {
      addCriterion("d.last_modified_by >=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThan(Long value) {
      addCriterion("d.last_modified_by <", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThanOrEqualTo(Long value) {
      addCriterion("d.last_modified_by <=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIn(List<Long> values) {
      addCriterion("d.last_modified_by in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotIn(List<Long> values) {
      addCriterion("d.last_modified_by not in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByBetween(Long value1, Long value2) {
      addCriterion("d.last_modified_by between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotBetween(Long value1, Long value2) {
      addCriterion("d.last_modified_by not between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNull() {
      addCriterion("d.last_modified_date is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNotNull() {
      addCriterion("d.last_modified_date is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateEqualTo(Date value) {
      addCriterion("d.last_modified_date =", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotEqualTo(Date value) {
      addCriterion("d.last_modified_date <>", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThan(Date value) {
      addCriterion("d.last_modified_date >", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("d.last_modified_date >=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThan(Date value) {
      addCriterion("d.last_modified_date <", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
      addCriterion("d.last_modified_date <=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIn(List<Date> values) {
      addCriterion("d.last_modified_date in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotIn(List<Date> values) {
      addCriterion("d.last_modified_date not in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
      addCriterion("d.last_modified_date between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
      addCriterion("d.last_modified_date not between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andTypeIsNull() {
      addCriterion("d.type is null");
      return (Criteria) this;
    }

    public Criteria andTypeIsNotNull() {
      addCriterion("d.type is not null");
      return (Criteria) this;
    }

    public Criteria andTypeEqualTo(String value) {
      addCriterion("d.type =", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotEqualTo(String value) {
      addCriterion("d.type <>", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThan(String value) {
      addCriterion("d.type >", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThanOrEqualTo(String value) {
      addCriterion("d.type >=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThan(String value) {
      addCriterion("d.type <", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThanOrEqualTo(String value) {
      addCriterion("d.type <=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLike(String value) {
      addCriterion("d.type like", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotLike(String value) {
      addCriterion("d.type not like", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeIn(List<String> values) {
      addCriterion("d.type in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotIn(List<String> values) {
      addCriterion("d.type not in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeBetween(String value1, String value2) {
      addCriterion("d.type between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotBetween(String value1, String value2) {
      addCriterion("d.type not between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andValueIsNull() {
      addCriterion("d.value is null");
      return (Criteria) this;
    }

    public Criteria andValueIsNotNull() {
      addCriterion("d.value is not null");
      return (Criteria) this;
    }

    public Criteria andValueEqualTo(String value) {
      addCriterion("d.value =", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotEqualTo(String value) {
      addCriterion("d.value <>", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueGreaterThan(String value) {
      addCriterion("d.value >", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueGreaterThanOrEqualTo(String value) {
      addCriterion("d.value >=", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueLessThan(String value) {
      addCriterion("d.value <", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueLessThanOrEqualTo(String value) {
      addCriterion("d.value <=", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueLike(String value) {
      addCriterion("d.value like", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotLike(String value) {
      addCriterion("d.value not like", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueIn(List<String> values) {
      addCriterion("d.value in", values, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotIn(List<String> values) {
      addCriterion("d.value not in", values, "value");
      return (Criteria) this;
    }

    public Criteria andValueBetween(String value1, String value2) {
      addCriterion("d.value between", value1, value2, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotBetween(String value1, String value2) {
      addCriterion("d.value not between", value1, value2, "value");
      return (Criteria) this;
    }

    public Criteria andLabelIsNull() {
      addCriterion("d.label is null");
      return (Criteria) this;
    }

    public Criteria andLabelIsNotNull() {
      addCriterion("d.label is not null");
      return (Criteria) this;
    }

    public Criteria andLabelEqualTo(String value) {
      addCriterion("d.label =", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotEqualTo(String value) {
      addCriterion("d.label <>", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelGreaterThan(String value) {
      addCriterion("d.label >", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelGreaterThanOrEqualTo(String value) {
      addCriterion("d.label >=", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelLessThan(String value) {
      addCriterion("d.label <", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelLessThanOrEqualTo(String value) {
      addCriterion("d.label <=", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelLike(String value) {
      addCriterion("d.label like", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotLike(String value) {
      addCriterion("d.label not like", value, "label");
      return (Criteria) this;
    }

    public Criteria andLabelIn(List<String> values) {
      addCriterion("d.label in", values, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotIn(List<String> values) {
      addCriterion("d.label not in", values, "label");
      return (Criteria) this;
    }

    public Criteria andLabelBetween(String value1, String value2) {
      addCriterion("d.label between", value1, value2, "label");
      return (Criteria) this;
    }

    public Criteria andLabelNotBetween(String value1, String value2) {
      addCriterion("d.label not between", value1, value2, "label");
      return (Criteria) this;
    }

    public Criteria andSortIsNull() {
      addCriterion("d.sort is null");
      return (Criteria) this;
    }

    public Criteria andSortIsNotNull() {
      addCriterion("d.sort is not null");
      return (Criteria) this;
    }

    public Criteria andSortEqualTo(Long value) {
      addCriterion("d.sort =", value, "sort");
      return (Criteria) this;
    }

    public Criteria andSortNotEqualTo(Long value) {
      addCriterion("d.sort <>", value, "sort");
      return (Criteria) this;
    }

    public Criteria andSortGreaterThan(Long value) {
      addCriterion("d.sort >", value, "sort");
      return (Criteria) this;
    }

    public Criteria andSortGreaterThanOrEqualTo(Long value) {
      addCriterion("d.sort >=", value, "sort");
      return (Criteria) this;
    }

    public Criteria andSortLessThan(Long value) {
      addCriterion("d.sort <", value, "sort");
      return (Criteria) this;
    }

    public Criteria andSortLessThanOrEqualTo(Long value) {
      addCriterion("d.sort <=", value, "sort");
      return (Criteria) this;
    }

    public Criteria andSortIn(List<Long> values) {
      addCriterion("d.sort in", values, "sort");
      return (Criteria) this;
    }

    public Criteria andSortNotIn(List<Long> values) {
      addCriterion("d.sort not in", values, "sort");
      return (Criteria) this;
    }

    public Criteria andSortBetween(Long value1, Long value2) {
      addCriterion("d.sort between", value1, value2, "sort");
      return (Criteria) this;
    }

    public Criteria andSortNotBetween(Long value1, Long value2) {
      addCriterion("d.sort not between", value1, value2, "sort");
      return (Criteria) this;
    }

    public Criteria andRemarksIsNull() {
      addCriterion("d.remarks is null");
      return (Criteria) this;
    }

    public Criteria andRemarksIsNotNull() {
      addCriterion("d.remarks is not null");
      return (Criteria) this;
    }

    public Criteria andRemarksEqualTo(String value) {
      addCriterion("d.remarks =", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotEqualTo(String value) {
      addCriterion("d.remarks <>", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksGreaterThan(String value) {
      addCriterion("d.remarks >", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksGreaterThanOrEqualTo(String value) {
      addCriterion("d.remarks >=", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksLessThan(String value) {
      addCriterion("d.remarks <", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksLessThanOrEqualTo(String value) {
      addCriterion("d.remarks <=", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksLike(String value) {
      addCriterion("d.remarks like", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotLike(String value) {
      addCriterion("d.remarks not like", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksIn(List<String> values) {
      addCriterion("d.remarks in", values, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotIn(List<String> values) {
      addCriterion("d.remarks not in", values, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksBetween(String value1, String value2) {
      addCriterion("d.remarks between", value1, value2, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotBetween(String value1, String value2) {
      addCriterion("d.remarks not between", value1, value2, "remarks");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_dict
   *
   * @mbg.generated do_not_delete_during_merge Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_dict
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}