package com.jez.modules.admin.system.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class GroupExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public GroupExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("g.id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("g.id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("g.id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("g.id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("g.id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("g.id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("g.id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("g.id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("g.id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("g.id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("g.id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("g.id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNull() {
      addCriterion("g.created_by is null");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNotNull() {
      addCriterion("g.created_by is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedByEqualTo(Long value) {
      addCriterion("g.created_by =", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotEqualTo(Long value) {
      addCriterion("g.created_by <>", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThan(Long value) {
      addCriterion("g.created_by >", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
      addCriterion("g.created_by >=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThan(Long value) {
      addCriterion("g.created_by <", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThanOrEqualTo(Long value) {
      addCriterion("g.created_by <=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByIn(List<Long> values) {
      addCriterion("g.created_by in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotIn(List<Long> values) {
      addCriterion("g.created_by not in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByBetween(Long value1, Long value2) {
      addCriterion("g.created_by between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotBetween(Long value1, Long value2) {
      addCriterion("g.created_by not between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNull() {
      addCriterion("g.created_date is null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNotNull() {
      addCriterion("g.created_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateEqualTo(Date value) {
      addCriterion("g.created_date =", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotEqualTo(Date value) {
      addCriterion("g.created_date <>", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThan(Date value) {
      addCriterion("g.created_date >", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("g.created_date >=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThan(Date value) {
      addCriterion("g.created_date <", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
      addCriterion("g.created_date <=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIn(List<Date> values) {
      addCriterion("g.created_date in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotIn(List<Date> values) {
      addCriterion("g.created_date not in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateBetween(Date value1, Date value2) {
      addCriterion("g.created_date between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
      addCriterion("g.created_date not between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNull() {
      addCriterion("g.last_modified_by is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNotNull() {
      addCriterion("g.last_modified_by is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByEqualTo(Long value) {
      addCriterion("g.last_modified_by =", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotEqualTo(Long value) {
      addCriterion("g.last_modified_by <>", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThan(Long value) {
      addCriterion("g.last_modified_by >", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThanOrEqualTo(Long value) {
      addCriterion("g.last_modified_by >=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThan(Long value) {
      addCriterion("g.last_modified_by <", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThanOrEqualTo(Long value) {
      addCriterion("g.last_modified_by <=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIn(List<Long> values) {
      addCriterion("g.last_modified_by in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotIn(List<Long> values) {
      addCriterion("g.last_modified_by not in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByBetween(Long value1, Long value2) {
      addCriterion("g.last_modified_by between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotBetween(Long value1, Long value2) {
      addCriterion("g.last_modified_by not between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNull() {
      addCriterion("g.last_modified_date is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNotNull() {
      addCriterion("g.last_modified_date is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateEqualTo(Date value) {
      addCriterion("g.last_modified_date =", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotEqualTo(Date value) {
      addCriterion("g.last_modified_date <>", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThan(Date value) {
      addCriterion("g.last_modified_date >", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("g.last_modified_date >=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThan(Date value) {
      addCriterion("g.last_modified_date <", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
      addCriterion("g.last_modified_date <=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIn(List<Date> values) {
      addCriterion("g.last_modified_date in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotIn(List<Date> values) {
      addCriterion("g.last_modified_date not in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
      addCriterion("g.last_modified_date between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
      addCriterion("g.last_modified_date not between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("g.name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("g.name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("g.name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("g.name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("g.name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("g.name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("g.name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("g.name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("g.name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("g.name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("g.name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("g.name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("g.name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("g.name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andCodeIsNull() {
      addCriterion("g.code is null");
      return (Criteria) this;
    }

    public Criteria andCodeIsNotNull() {
      addCriterion("g.code is not null");
      return (Criteria) this;
    }

    public Criteria andCodeEqualTo(String value) {
      addCriterion("g.code =", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotEqualTo(String value) {
      addCriterion("g.code <>", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThan(String value) {
      addCriterion("g.code >", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThanOrEqualTo(String value) {
      addCriterion("g.code >=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThan(String value) {
      addCriterion("g.code <", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThanOrEqualTo(String value) {
      addCriterion("g.code <=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLike(String value) {
      addCriterion("g.code like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotLike(String value) {
      addCriterion("g.code not like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeIn(List<String> values) {
      addCriterion("g.code in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotIn(List<String> values) {
      addCriterion("g.code not in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeBetween(String value1, String value2) {
      addCriterion("g.code between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotBetween(String value1, String value2) {
      addCriterion("g.code not between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andRemarksIsNull() {
      addCriterion("g.remarks is null");
      return (Criteria) this;
    }

    public Criteria andRemarksIsNotNull() {
      addCriterion("g.remarks is not null");
      return (Criteria) this;
    }

    public Criteria andRemarksEqualTo(String value) {
      addCriterion("g.remarks =", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotEqualTo(String value) {
      addCriterion("g.remarks <>", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksGreaterThan(String value) {
      addCriterion("g.remarks >", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksGreaterThanOrEqualTo(String value) {
      addCriterion("g.remarks >=", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksLessThan(String value) {
      addCriterion("g.remarks <", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksLessThanOrEqualTo(String value) {
      addCriterion("g.remarks <=", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksLike(String value) {
      addCriterion("g.remarks like", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotLike(String value) {
      addCriterion("g.remarks not like", value, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksIn(List<String> values) {
      addCriterion("g.remarks in", values, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotIn(List<String> values) {
      addCriterion("g.remarks not in", values, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksBetween(String value1, String value2) {
      addCriterion("g.remarks between", value1, value2, "remarks");
      return (Criteria) this;
    }

    public Criteria andRemarksNotBetween(String value1, String value2) {
      addCriterion("g.remarks not between", value1, value2, "remarks");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_group
   *
   * @mbg.generated do_not_delete_during_merge Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_group
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}