package com.jez.modules.admin.system.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OfficeExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public OfficeExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("o.id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("o.id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("o.id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("o.id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("o.id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("o.id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("o.id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("o.id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("o.id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("o.id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("o.id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("o.id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNull() {
      addCriterion("o.created_by is null");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNotNull() {
      addCriterion("o.created_by is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedByEqualTo(Long value) {
      addCriterion("o.created_by =", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotEqualTo(Long value) {
      addCriterion("o.created_by <>", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThan(Long value) {
      addCriterion("o.created_by >", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
      addCriterion("o.created_by >=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThan(Long value) {
      addCriterion("o.created_by <", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThanOrEqualTo(Long value) {
      addCriterion("o.created_by <=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByIn(List<Long> values) {
      addCriterion("o.created_by in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotIn(List<Long> values) {
      addCriterion("o.created_by not in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByBetween(Long value1, Long value2) {
      addCriterion("o.created_by between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotBetween(Long value1, Long value2) {
      addCriterion("o.created_by not between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNull() {
      addCriterion("o.created_date is null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNotNull() {
      addCriterion("o.created_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateEqualTo(Date value) {
      addCriterion("o.created_date =", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotEqualTo(Date value) {
      addCriterion("o.created_date <>", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThan(Date value) {
      addCriterion("o.created_date >", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("o.created_date >=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThan(Date value) {
      addCriterion("o.created_date <", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
      addCriterion("o.created_date <=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIn(List<Date> values) {
      addCriterion("o.created_date in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotIn(List<Date> values) {
      addCriterion("o.created_date not in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateBetween(Date value1, Date value2) {
      addCriterion("o.created_date between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
      addCriterion("o.created_date not between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNull() {
      addCriterion("o.last_modified_by is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNotNull() {
      addCriterion("o.last_modified_by is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByEqualTo(Long value) {
      addCriterion("o.last_modified_by =", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotEqualTo(Long value) {
      addCriterion("o.last_modified_by <>", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThan(Long value) {
      addCriterion("o.last_modified_by >", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThanOrEqualTo(Long value) {
      addCriterion("o.last_modified_by >=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThan(Long value) {
      addCriterion("o.last_modified_by <", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThanOrEqualTo(Long value) {
      addCriterion("o.last_modified_by <=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIn(List<Long> values) {
      addCriterion("o.last_modified_by in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotIn(List<Long> values) {
      addCriterion("o.last_modified_by not in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByBetween(Long value1, Long value2) {
      addCriterion("o.last_modified_by between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotBetween(Long value1, Long value2) {
      addCriterion("o.last_modified_by not between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNull() {
      addCriterion("o.last_modified_date is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNotNull() {
      addCriterion("o.last_modified_date is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateEqualTo(Date value) {
      addCriterion("o.last_modified_date =", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotEqualTo(Date value) {
      addCriterion("o.last_modified_date <>", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThan(Date value) {
      addCriterion("o.last_modified_date >", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("o.last_modified_date >=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThan(Date value) {
      addCriterion("o.last_modified_date <", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
      addCriterion("o.last_modified_date <=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIn(List<Date> values) {
      addCriterion("o.last_modified_date in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotIn(List<Date> values) {
      addCriterion("o.last_modified_date not in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
      addCriterion("o.last_modified_date between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
      addCriterion("o.last_modified_date not between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andParentIdIsNull() {
      addCriterion("o.parent_id is null");
      return (Criteria) this;
    }

    public Criteria andParentIdIsNotNull() {
      addCriterion("o.parent_id is not null");
      return (Criteria) this;
    }

    public Criteria andParentIdEqualTo(Long value) {
      addCriterion("o.parent_id =", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdNotEqualTo(Long value) {
      addCriterion("o.parent_id <>", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdGreaterThan(Long value) {
      addCriterion("o.parent_id >", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
      addCriterion("o.parent_id >=", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdLessThan(Long value) {
      addCriterion("o.parent_id <", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdLessThanOrEqualTo(Long value) {
      addCriterion("o.parent_id <=", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdIn(List<Long> values) {
      addCriterion("o.parent_id in", values, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdNotIn(List<Long> values) {
      addCriterion("o.parent_id not in", values, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdBetween(Long value1, Long value2) {
      addCriterion("o.parent_id between", value1, value2, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdNotBetween(Long value1, Long value2) {
      addCriterion("o.parent_id not between", value1, value2, "parentId");
      return (Criteria) this;
    }

    public Criteria andLftIsNull() {
      addCriterion("o.lft is null");
      return (Criteria) this;
    }

    public Criteria andLftIsNotNull() {
      addCriterion("o.lft is not null");
      return (Criteria) this;
    }

    public Criteria andLftEqualTo(Long value) {
      addCriterion("o.lft =", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftNotEqualTo(Long value) {
      addCriterion("o.lft <>", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftGreaterThan(Long value) {
      addCriterion("o.lft >", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftGreaterThanOrEqualTo(Long value) {
      addCriterion("o.lft >=", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftLessThan(Long value) {
      addCriterion("o.lft <", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftLessThanOrEqualTo(Long value) {
      addCriterion("o.lft <=", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftIn(List<Long> values) {
      addCriterion("o.lft in", values, "lft");
      return (Criteria) this;
    }

    public Criteria andLftNotIn(List<Long> values) {
      addCriterion("o.lft not in", values, "lft");
      return (Criteria) this;
    }

    public Criteria andLftBetween(Long value1, Long value2) {
      addCriterion("o.lft between", value1, value2, "lft");
      return (Criteria) this;
    }

    public Criteria andLftNotBetween(Long value1, Long value2) {
      addCriterion("o.lft not between", value1, value2, "lft");
      return (Criteria) this;
    }

    public Criteria andRtIsNull() {
      addCriterion("o.rt is null");
      return (Criteria) this;
    }

    public Criteria andRtIsNotNull() {
      addCriterion("o.rt is not null");
      return (Criteria) this;
    }

    public Criteria andRtEqualTo(Long value) {
      addCriterion("o.rt =", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtNotEqualTo(Long value) {
      addCriterion("o.rt <>", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtGreaterThan(Long value) {
      addCriterion("o.rt >", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtGreaterThanOrEqualTo(Long value) {
      addCriterion("o.rt >=", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtLessThan(Long value) {
      addCriterion("o.rt <", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtLessThanOrEqualTo(Long value) {
      addCriterion("o.rt <=", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtIn(List<Long> values) {
      addCriterion("o.rt in", values, "rt");
      return (Criteria) this;
    }

    public Criteria andRtNotIn(List<Long> values) {
      addCriterion("o.rt not in", values, "rt");
      return (Criteria) this;
    }

    public Criteria andRtBetween(Long value1, Long value2) {
      addCriterion("o.rt between", value1, value2, "rt");
      return (Criteria) this;
    }

    public Criteria andRtNotBetween(Long value1, Long value2) {
      addCriterion("o.rt not between", value1, value2, "rt");
      return (Criteria) this;
    }

    public Criteria andLevelIsNull() {
      addCriterion("o.level is null");
      return (Criteria) this;
    }

    public Criteria andLevelIsNotNull() {
      addCriterion("o.level is not null");
      return (Criteria) this;
    }

    public Criteria andLevelEqualTo(Integer value) {
      addCriterion("o.level =", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelNotEqualTo(Integer value) {
      addCriterion("o.level <>", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelGreaterThan(Integer value) {
      addCriterion("o.level >", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
      addCriterion("o.level >=", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelLessThan(Integer value) {
      addCriterion("o.level <", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelLessThanOrEqualTo(Integer value) {
      addCriterion("o.level <=", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelIn(List<Integer> values) {
      addCriterion("o.level in", values, "level");
      return (Criteria) this;
    }

    public Criteria andLevelNotIn(List<Integer> values) {
      addCriterion("o.level not in", values, "level");
      return (Criteria) this;
    }

    public Criteria andLevelBetween(Integer value1, Integer value2) {
      addCriterion("o.level between", value1, value2, "level");
      return (Criteria) this;
    }

    public Criteria andLevelNotBetween(Integer value1, Integer value2) {
      addCriterion("o.level not between", value1, value2, "level");
      return (Criteria) this;
    }

    public Criteria andTypeIsNull() {
      addCriterion("o.type is null");
      return (Criteria) this;
    }

    public Criteria andTypeIsNotNull() {
      addCriterion("o.type is not null");
      return (Criteria) this;
    }

    public Criteria andTypeEqualTo(Integer value) {
      addCriterion("o.type =", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotEqualTo(Integer value) {
      addCriterion("o.type <>", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThan(Integer value) {
      addCriterion("o.type >", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
      addCriterion("o.type >=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThan(Integer value) {
      addCriterion("o.type <", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThanOrEqualTo(Integer value) {
      addCriterion("o.type <=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeIn(List<Integer> values) {
      addCriterion("o.type in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotIn(List<Integer> values) {
      addCriterion("o.type not in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeBetween(Integer value1, Integer value2) {
      addCriterion("o.type between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotBetween(Integer value1, Integer value2) {
      addCriterion("o.type not between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("o.name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("o.name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("o.name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("o.name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("o.name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("o.name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("o.name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("o.name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("o.name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("o.name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("o.name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("o.name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("o.name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("o.name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andCodeIsNull() {
      addCriterion("o.code is null");
      return (Criteria) this;
    }

    public Criteria andCodeIsNotNull() {
      addCriterion("o.code is not null");
      return (Criteria) this;
    }

    public Criteria andCodeEqualTo(String value) {
      addCriterion("o.code =", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotEqualTo(String value) {
      addCriterion("o.code <>", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThan(String value) {
      addCriterion("o.code >", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeGreaterThanOrEqualTo(String value) {
      addCriterion("o.code >=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThan(String value) {
      addCriterion("o.code <", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLessThanOrEqualTo(String value) {
      addCriterion("o.code <=", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeLike(String value) {
      addCriterion("o.code like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotLike(String value) {
      addCriterion("o.code not like", value, "code");
      return (Criteria) this;
    }

    public Criteria andCodeIn(List<String> values) {
      addCriterion("o.code in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotIn(List<String> values) {
      addCriterion("o.code not in", values, "code");
      return (Criteria) this;
    }

    public Criteria andCodeBetween(String value1, String value2) {
      addCriterion("o.code between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andCodeNotBetween(String value1, String value2) {
      addCriterion("o.code not between", value1, value2, "code");
      return (Criteria) this;
    }

    public Criteria andShortNameIsNull() {
      addCriterion("o.short_name is null");
      return (Criteria) this;
    }

    public Criteria andShortNameIsNotNull() {
      addCriterion("o.short_name is not null");
      return (Criteria) this;
    }

    public Criteria andShortNameEqualTo(String value) {
      addCriterion("o.short_name =", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameNotEqualTo(String value) {
      addCriterion("o.short_name <>", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameGreaterThan(String value) {
      addCriterion("o.short_name >", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameGreaterThanOrEqualTo(String value) {
      addCriterion("o.short_name >=", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameLessThan(String value) {
      addCriterion("o.short_name <", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameLessThanOrEqualTo(String value) {
      addCriterion("o.short_name <=", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameLike(String value) {
      addCriterion("o.short_name like", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameNotLike(String value) {
      addCriterion("o.short_name not like", value, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameIn(List<String> values) {
      addCriterion("o.short_name in", values, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameNotIn(List<String> values) {
      addCriterion("o.short_name not in", values, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameBetween(String value1, String value2) {
      addCriterion("o.short_name between", value1, value2, "shortName");
      return (Criteria) this;
    }

    public Criteria andShortNameNotBetween(String value1, String value2) {
      addCriterion("o.short_name not between", value1, value2, "shortName");
      return (Criteria) this;
    }

    public Criteria andFunctionsIsNull() {
      addCriterion("o.functions is null");
      return (Criteria) this;
    }

    public Criteria andFunctionsIsNotNull() {
      addCriterion("o.functions is not null");
      return (Criteria) this;
    }

    public Criteria andFunctionsEqualTo(String value) {
      addCriterion("o.functions =", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsNotEqualTo(String value) {
      addCriterion("o.functions <>", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsGreaterThan(String value) {
      addCriterion("o.functions >", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsGreaterThanOrEqualTo(String value) {
      addCriterion("o.functions >=", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsLessThan(String value) {
      addCriterion("o.functions <", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsLessThanOrEqualTo(String value) {
      addCriterion("o.functions <=", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsLike(String value) {
      addCriterion("o.functions like", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsNotLike(String value) {
      addCriterion("o.functions not like", value, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsIn(List<String> values) {
      addCriterion("o.functions in", values, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsNotIn(List<String> values) {
      addCriterion("o.functions not in", values, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsBetween(String value1, String value2) {
      addCriterion("o.functions between", value1, value2, "functions");
      return (Criteria) this;
    }

    public Criteria andFunctionsNotBetween(String value1, String value2) {
      addCriterion("o.functions not between", value1, value2, "functions");
      return (Criteria) this;
    }

    public Criteria andAddressIsNull() {
      addCriterion("o.address is null");
      return (Criteria) this;
    }

    public Criteria andAddressIsNotNull() {
      addCriterion("o.address is not null");
      return (Criteria) this;
    }

    public Criteria andAddressEqualTo(String value) {
      addCriterion("o.address =", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotEqualTo(String value) {
      addCriterion("o.address <>", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressGreaterThan(String value) {
      addCriterion("o.address >", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressGreaterThanOrEqualTo(String value) {
      addCriterion("o.address >=", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLessThan(String value) {
      addCriterion("o.address <", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLessThanOrEqualTo(String value) {
      addCriterion("o.address <=", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLike(String value) {
      addCriterion("o.address like", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotLike(String value) {
      addCriterion("o.address not like", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressIn(List<String> values) {
      addCriterion("o.address in", values, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotIn(List<String> values) {
      addCriterion("o.address not in", values, "address");
      return (Criteria) this;
    }

    public Criteria andAddressBetween(String value1, String value2) {
      addCriterion("o.address between", value1, value2, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotBetween(String value1, String value2) {
      addCriterion("o.address not between", value1, value2, "address");
      return (Criteria) this;
    }

    public Criteria andAddressDetailIsNull() {
      addCriterion("o.address_detail is null");
      return (Criteria) this;
    }

    public Criteria andAddressDetailIsNotNull() {
      addCriterion("o.address_detail is not null");
      return (Criteria) this;
    }

    public Criteria andAddressDetailEqualTo(String value) {
      addCriterion("o.address_detail =", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotEqualTo(String value) {
      addCriterion("o.address_detail <>", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailGreaterThan(String value) {
      addCriterion("o.address_detail >", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailGreaterThanOrEqualTo(String value) {
      addCriterion("o.address_detail >=", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailLessThan(String value) {
      addCriterion("o.address_detail <", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailLessThanOrEqualTo(String value) {
      addCriterion("o.address_detail <=", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailLike(String value) {
      addCriterion("o.address_detail like", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotLike(String value) {
      addCriterion("o.address_detail not like", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailIn(List<String> values) {
      addCriterion("o.address_detail in", values, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotIn(List<String> values) {
      addCriterion("o.address_detail not in", values, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailBetween(String value1, String value2) {
      addCriterion("o.address_detail between", value1, value2, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotBetween(String value1, String value2) {
      addCriterion("o.address_detail not between", value1, value2, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andZipCodeIsNull() {
      addCriterion("o.zip_code is null");
      return (Criteria) this;
    }

    public Criteria andZipCodeIsNotNull() {
      addCriterion("o.zip_code is not null");
      return (Criteria) this;
    }

    public Criteria andZipCodeEqualTo(String value) {
      addCriterion("o.zip_code =", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotEqualTo(String value) {
      addCriterion("o.zip_code <>", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeGreaterThan(String value) {
      addCriterion("o.zip_code >", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
      addCriterion("o.zip_code >=", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeLessThan(String value) {
      addCriterion("o.zip_code <", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeLessThanOrEqualTo(String value) {
      addCriterion("o.zip_code <=", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeLike(String value) {
      addCriterion("o.zip_code like", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotLike(String value) {
      addCriterion("o.zip_code not like", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeIn(List<String> values) {
      addCriterion("o.zip_code in", values, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotIn(List<String> values) {
      addCriterion("o.zip_code not in", values, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeBetween(String value1, String value2) {
      addCriterion("o.zip_code between", value1, value2, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotBetween(String value1, String value2) {
      addCriterion("o.zip_code not between", value1, value2, "zipCode");
      return (Criteria) this;
    }

    public Criteria andTelephoneIsNull() {
      addCriterion("o.telephone is null");
      return (Criteria) this;
    }

    public Criteria andTelephoneIsNotNull() {
      addCriterion("o.telephone is not null");
      return (Criteria) this;
    }

    public Criteria andTelephoneEqualTo(String value) {
      addCriterion("o.telephone =", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotEqualTo(String value) {
      addCriterion("o.telephone <>", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneGreaterThan(String value) {
      addCriterion("o.telephone >", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
      addCriterion("o.telephone >=", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneLessThan(String value) {
      addCriterion("o.telephone <", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneLessThanOrEqualTo(String value) {
      addCriterion("o.telephone <=", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneLike(String value) {
      addCriterion("o.telephone like", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotLike(String value) {
      addCriterion("o.telephone not like", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneIn(List<String> values) {
      addCriterion("o.telephone in", values, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotIn(List<String> values) {
      addCriterion("o.telephone not in", values, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneBetween(String value1, String value2) {
      addCriterion("o.telephone between", value1, value2, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotBetween(String value1, String value2) {
      addCriterion("o.telephone not between", value1, value2, "telephone");
      return (Criteria) this;
    }

    public Criteria andEmailIsNull() {
      addCriterion("o.email is null");
      return (Criteria) this;
    }

    public Criteria andEmailIsNotNull() {
      addCriterion("o.email is not null");
      return (Criteria) this;
    }

    public Criteria andEmailEqualTo(String value) {
      addCriterion("o.email =", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotEqualTo(String value) {
      addCriterion("o.email <>", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailGreaterThan(String value) {
      addCriterion("o.email >", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailGreaterThanOrEqualTo(String value) {
      addCriterion("o.email >=", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLessThan(String value) {
      addCriterion("o.email <", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLessThanOrEqualTo(String value) {
      addCriterion("o.email <=", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLike(String value) {
      addCriterion("o.email like", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotLike(String value) {
      addCriterion("o.email not like", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailIn(List<String> values) {
      addCriterion("o.email in", values, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotIn(List<String> values) {
      addCriterion("o.email not in", values, "email");
      return (Criteria) this;
    }

    public Criteria andEmailBetween(String value1, String value2) {
      addCriterion("o.email between", value1, value2, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotBetween(String value1, String value2) {
      addCriterion("o.email not between", value1, value2, "email");
      return (Criteria) this;
    }

    public Criteria andFaxIsNull() {
      addCriterion("o.fax is null");
      return (Criteria) this;
    }

    public Criteria andFaxIsNotNull() {
      addCriterion("o.fax is not null");
      return (Criteria) this;
    }

    public Criteria andFaxEqualTo(String value) {
      addCriterion("o.fax =", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxNotEqualTo(String value) {
      addCriterion("o.fax <>", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxGreaterThan(String value) {
      addCriterion("o.fax >", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxGreaterThanOrEqualTo(String value) {
      addCriterion("o.fax >=", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxLessThan(String value) {
      addCriterion("o.fax <", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxLessThanOrEqualTo(String value) {
      addCriterion("o.fax <=", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxLike(String value) {
      addCriterion("o.fax like", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxNotLike(String value) {
      addCriterion("o.fax not like", value, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxIn(List<String> values) {
      addCriterion("o.fax in", values, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxNotIn(List<String> values) {
      addCriterion("o.fax not in", values, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxBetween(String value1, String value2) {
      addCriterion("o.fax between", value1, value2, "fax");
      return (Criteria) this;
    }

    public Criteria andFaxNotBetween(String value1, String value2) {
      addCriterion("o.fax not between", value1, value2, "fax");
      return (Criteria) this;
    }

    public Criteria andLeaderIdIsNull() {
      addCriterion("o.leader_id is null");
      return (Criteria) this;
    }

    public Criteria andLeaderIdIsNotNull() {
      addCriterion("o.leader_id is not null");
      return (Criteria) this;
    }

    public Criteria andLeaderIdEqualTo(Long value) {
      addCriterion("o.leader_id =", value, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdNotEqualTo(Long value) {
      addCriterion("o.leader_id <>", value, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdGreaterThan(Long value) {
      addCriterion("o.leader_id >", value, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdGreaterThanOrEqualTo(Long value) {
      addCriterion("o.leader_id >=", value, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdLessThan(Long value) {
      addCriterion("o.leader_id <", value, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdLessThanOrEqualTo(Long value) {
      addCriterion("o.leader_id <=", value, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdIn(List<Long> values) {
      addCriterion("o.leader_id in", values, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdNotIn(List<Long> values) {
      addCriterion("o.leader_id not in", values, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdBetween(Long value1, Long value2) {
      addCriterion("o.leader_id between", value1, value2, "leaderId");
      return (Criteria) this;
    }

    public Criteria andLeaderIdNotBetween(Long value1, Long value2) {
      addCriterion("o.leader_id not between", value1, value2, "leaderId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdIsNull() {
      addCriterion("o.contact_person_id is null");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdIsNotNull() {
      addCriterion("o.contact_person_id is not null");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdEqualTo(Long value) {
      addCriterion("o.contact_person_id =", value, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdNotEqualTo(Long value) {
      addCriterion("o.contact_person_id <>", value, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdGreaterThan(Long value) {
      addCriterion("o.contact_person_id >", value, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdGreaterThanOrEqualTo(Long value) {
      addCriterion("o.contact_person_id >=", value, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdLessThan(Long value) {
      addCriterion("o.contact_person_id <", value, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdLessThanOrEqualTo(Long value) {
      addCriterion("o.contact_person_id <=", value, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdIn(List<Long> values) {
      addCriterion("o.contact_person_id in", values, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdNotIn(List<Long> values) {
      addCriterion("o.contact_person_id not in", values, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdBetween(Long value1, Long value2) {
      addCriterion("o.contact_person_id between", value1, value2, "contactPersonId");
      return (Criteria) this;
    }

    public Criteria andContactPersonIdNotBetween(Long value1, Long value2) {
      addCriterion("o.contact_person_id not between", value1, value2, "contactPersonId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_office
   *
   * @mbg.generated do_not_delete_during_merge Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_office
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}