package com.jez.modules.admin.system.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OperationLogExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public OperationLogExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("ol.id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("ol.id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("ol.id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("ol.id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("ol.id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("ol.id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("ol.id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("ol.id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("ol.id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("ol.id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("ol.id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("ol.id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNull() {
      addCriterion("ol.user_id is null");
      return (Criteria) this;
    }

    public Criteria andUserIdIsNotNull() {
      addCriterion("ol.user_id is not null");
      return (Criteria) this;
    }

    public Criteria andUserIdEqualTo(Long value) {
      addCriterion("ol.user_id =", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotEqualTo(Long value) {
      addCriterion("ol.user_id <>", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThan(Long value) {
      addCriterion("ol.user_id >", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
      addCriterion("ol.user_id >=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThan(Long value) {
      addCriterion("ol.user_id <", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdLessThanOrEqualTo(Long value) {
      addCriterion("ol.user_id <=", value, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdIn(List<Long> values) {
      addCriterion("ol.user_id in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotIn(List<Long> values) {
      addCriterion("ol.user_id not in", values, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdBetween(Long value1, Long value2) {
      addCriterion("ol.user_id between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andUserIdNotBetween(Long value1, Long value2) {
      addCriterion("ol.user_id not between", value1, value2, "userId");
      return (Criteria) this;
    }

    public Criteria andOperateTimeIsNull() {
      addCriterion("ol.operate_time is null");
      return (Criteria) this;
    }

    public Criteria andOperateTimeIsNotNull() {
      addCriterion("ol.operate_time is not null");
      return (Criteria) this;
    }

    public Criteria andOperateTimeEqualTo(Date value) {
      addCriterion("ol.operate_time =", value, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeNotEqualTo(Date value) {
      addCriterion("ol.operate_time <>", value, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeGreaterThan(Date value) {
      addCriterion("ol.operate_time >", value, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("ol.operate_time >=", value, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeLessThan(Date value) {
      addCriterion("ol.operate_time <", value, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeLessThanOrEqualTo(Date value) {
      addCriterion("ol.operate_time <=", value, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeIn(List<Date> values) {
      addCriterion("ol.operate_time in", values, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeNotIn(List<Date> values) {
      addCriterion("ol.operate_time not in", values, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeBetween(Date value1, Date value2) {
      addCriterion("ol.operate_time between", value1, value2, "operateTime");
      return (Criteria) this;
    }

    public Criteria andOperateTimeNotBetween(Date value1, Date value2) {
      addCriterion("ol.operate_time not between", value1, value2, "operateTime");
      return (Criteria) this;
    }

    public Criteria andTitleIsNull() {
      addCriterion("ol.title is null");
      return (Criteria) this;
    }

    public Criteria andTitleIsNotNull() {
      addCriterion("ol.title is not null");
      return (Criteria) this;
    }

    public Criteria andTitleEqualTo(String value) {
      addCriterion("ol.title =", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotEqualTo(String value) {
      addCriterion("ol.title <>", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleGreaterThan(String value) {
      addCriterion("ol.title >", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleGreaterThanOrEqualTo(String value) {
      addCriterion("ol.title >=", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLessThan(String value) {
      addCriterion("ol.title <", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLessThanOrEqualTo(String value) {
      addCriterion("ol.title <=", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleLike(String value) {
      addCriterion("ol.title like", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotLike(String value) {
      addCriterion("ol.title not like", value, "title");
      return (Criteria) this;
    }

    public Criteria andTitleIn(List<String> values) {
      addCriterion("ol.title in", values, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotIn(List<String> values) {
      addCriterion("ol.title not in", values, "title");
      return (Criteria) this;
    }

    public Criteria andTitleBetween(String value1, String value2) {
      addCriterion("ol.title between", value1, value2, "title");
      return (Criteria) this;
    }

    public Criteria andTitleNotBetween(String value1, String value2) {
      addCriterion("ol.title not between", value1, value2, "title");
      return (Criteria) this;
    }

    public Criteria andServerPathIsNull() {
      addCriterion("ol.server_path is null");
      return (Criteria) this;
    }

    public Criteria andServerPathIsNotNull() {
      addCriterion("ol.server_path is not null");
      return (Criteria) this;
    }

    public Criteria andServerPathEqualTo(String value) {
      addCriterion("ol.server_path =", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathNotEqualTo(String value) {
      addCriterion("ol.server_path <>", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathGreaterThan(String value) {
      addCriterion("ol.server_path >", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathGreaterThanOrEqualTo(String value) {
      addCriterion("ol.server_path >=", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathLessThan(String value) {
      addCriterion("ol.server_path <", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathLessThanOrEqualTo(String value) {
      addCriterion("ol.server_path <=", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathLike(String value) {
      addCriterion("ol.server_path like", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathNotLike(String value) {
      addCriterion("ol.server_path not like", value, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathIn(List<String> values) {
      addCriterion("ol.server_path in", values, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathNotIn(List<String> values) {
      addCriterion("ol.server_path not in", values, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathBetween(String value1, String value2) {
      addCriterion("ol.server_path between", value1, value2, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServerPathNotBetween(String value1, String value2) {
      addCriterion("ol.server_path not between", value1, value2, "serverPath");
      return (Criteria) this;
    }

    public Criteria andServletPathIsNull() {
      addCriterion("ol.servlet_path is null");
      return (Criteria) this;
    }

    public Criteria andServletPathIsNotNull() {
      addCriterion("ol.servlet_path is not null");
      return (Criteria) this;
    }

    public Criteria andServletPathEqualTo(String value) {
      addCriterion("ol.servlet_path =", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathNotEqualTo(String value) {
      addCriterion("ol.servlet_path <>", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathGreaterThan(String value) {
      addCriterion("ol.servlet_path >", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathGreaterThanOrEqualTo(String value) {
      addCriterion("ol.servlet_path >=", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathLessThan(String value) {
      addCriterion("ol.servlet_path <", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathLessThanOrEqualTo(String value) {
      addCriterion("ol.servlet_path <=", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathLike(String value) {
      addCriterion("ol.servlet_path like", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathNotLike(String value) {
      addCriterion("ol.servlet_path not like", value, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathIn(List<String> values) {
      addCriterion("ol.servlet_path in", values, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathNotIn(List<String> values) {
      addCriterion("ol.servlet_path not in", values, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathBetween(String value1, String value2) {
      addCriterion("ol.servlet_path between", value1, value2, "servletPath");
      return (Criteria) this;
    }

    public Criteria andServletPathNotBetween(String value1, String value2) {
      addCriterion("ol.servlet_path not between", value1, value2, "servletPath");
      return (Criteria) this;
    }

    public Criteria andMethodIsNull() {
      addCriterion("ol.method is null");
      return (Criteria) this;
    }

    public Criteria andMethodIsNotNull() {
      addCriterion("ol.method is not null");
      return (Criteria) this;
    }

    public Criteria andMethodEqualTo(String value) {
      addCriterion("ol.method =", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotEqualTo(String value) {
      addCriterion("ol.method <>", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodGreaterThan(String value) {
      addCriterion("ol.method >", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodGreaterThanOrEqualTo(String value) {
      addCriterion("ol.method >=", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodLessThan(String value) {
      addCriterion("ol.method <", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodLessThanOrEqualTo(String value) {
      addCriterion("ol.method <=", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodLike(String value) {
      addCriterion("ol.method like", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotLike(String value) {
      addCriterion("ol.method not like", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodIn(List<String> values) {
      addCriterion("ol.method in", values, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotIn(List<String> values) {
      addCriterion("ol.method not in", values, "method");
      return (Criteria) this;
    }

    public Criteria andMethodBetween(String value1, String value2) {
      addCriterion("ol.method between", value1, value2, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotBetween(String value1, String value2) {
      addCriterion("ol.method not between", value1, value2, "method");
      return (Criteria) this;
    }

    public Criteria andResponseStatusIsNull() {
      addCriterion("ol.response_status is null");
      return (Criteria) this;
    }

    public Criteria andResponseStatusIsNotNull() {
      addCriterion("ol.response_status is not null");
      return (Criteria) this;
    }

    public Criteria andResponseStatusEqualTo(Integer value) {
      addCriterion("ol.response_status =", value, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusNotEqualTo(Integer value) {
      addCriterion("ol.response_status <>", value, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusGreaterThan(Integer value) {
      addCriterion("ol.response_status >", value, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusGreaterThanOrEqualTo(Integer value) {
      addCriterion("ol.response_status >=", value, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusLessThan(Integer value) {
      addCriterion("ol.response_status <", value, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusLessThanOrEqualTo(Integer value) {
      addCriterion("ol.response_status <=", value, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusIn(List<Integer> values) {
      addCriterion("ol.response_status in", values, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusNotIn(List<Integer> values) {
      addCriterion("ol.response_status not in", values, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusBetween(Integer value1, Integer value2) {
      addCriterion("ol.response_status between", value1, value2, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseStatusNotBetween(Integer value1, Integer value2) {
      addCriterion("ol.response_status not between", value1, value2, "responseStatus");
      return (Criteria) this;
    }

    public Criteria andResponseMillisIsNull() {
      addCriterion("ol.response_millis is null");
      return (Criteria) this;
    }

    public Criteria andResponseMillisIsNotNull() {
      addCriterion("ol.response_millis is not null");
      return (Criteria) this;
    }

    public Criteria andResponseMillisEqualTo(Long value) {
      addCriterion("ol.response_millis =", value, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisNotEqualTo(Long value) {
      addCriterion("ol.response_millis <>", value, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisGreaterThan(Long value) {
      addCriterion("ol.response_millis >", value, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisGreaterThanOrEqualTo(Long value) {
      addCriterion("ol.response_millis >=", value, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisLessThan(Long value) {
      addCriterion("ol.response_millis <", value, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisLessThanOrEqualTo(Long value) {
      addCriterion("ol.response_millis <=", value, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisIn(List<Long> values) {
      addCriterion("ol.response_millis in", values, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisNotIn(List<Long> values) {
      addCriterion("ol.response_millis not in", values, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisBetween(Long value1, Long value2) {
      addCriterion("ol.response_millis between", value1, value2, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andResponseMillisNotBetween(Long value1, Long value2) {
      addCriterion("ol.response_millis not between", value1, value2, "responseMillis");
      return (Criteria) this;
    }

    public Criteria andClientIpIsNull() {
      addCriterion("ol.client_ip is null");
      return (Criteria) this;
    }

    public Criteria andClientIpIsNotNull() {
      addCriterion("ol.client_ip is not null");
      return (Criteria) this;
    }

    public Criteria andClientIpEqualTo(String value) {
      addCriterion("ol.client_ip =", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpNotEqualTo(String value) {
      addCriterion("ol.client_ip <>", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpGreaterThan(String value) {
      addCriterion("ol.client_ip >", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpGreaterThanOrEqualTo(String value) {
      addCriterion("ol.client_ip >=", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpLessThan(String value) {
      addCriterion("ol.client_ip <", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpLessThanOrEqualTo(String value) {
      addCriterion("ol.client_ip <=", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpLike(String value) {
      addCriterion("ol.client_ip like", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpNotLike(String value) {
      addCriterion("ol.client_ip not like", value, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpIn(List<String> values) {
      addCriterion("ol.client_ip in", values, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpNotIn(List<String> values) {
      addCriterion("ol.client_ip not in", values, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpBetween(String value1, String value2) {
      addCriterion("ol.client_ip between", value1, value2, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientIpNotBetween(String value1, String value2) {
      addCriterion("ol.client_ip not between", value1, value2, "clientIp");
      return (Criteria) this;
    }

    public Criteria andClientDeviceIsNull() {
      addCriterion("ol.client_device is null");
      return (Criteria) this;
    }

    public Criteria andClientDeviceIsNotNull() {
      addCriterion("ol.client_device is not null");
      return (Criteria) this;
    }

    public Criteria andClientDeviceEqualTo(String value) {
      addCriterion("ol.client_device =", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceNotEqualTo(String value) {
      addCriterion("ol.client_device <>", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceGreaterThan(String value) {
      addCriterion("ol.client_device >", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceGreaterThanOrEqualTo(String value) {
      addCriterion("ol.client_device >=", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceLessThan(String value) {
      addCriterion("ol.client_device <", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceLessThanOrEqualTo(String value) {
      addCriterion("ol.client_device <=", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceLike(String value) {
      addCriterion("ol.client_device like", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceNotLike(String value) {
      addCriterion("ol.client_device not like", value, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceIn(List<String> values) {
      addCriterion("ol.client_device in", values, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceNotIn(List<String> values) {
      addCriterion("ol.client_device not in", values, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceBetween(String value1, String value2) {
      addCriterion("ol.client_device between", value1, value2, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientDeviceNotBetween(String value1, String value2) {
      addCriterion("ol.client_device not between", value1, value2, "clientDevice");
      return (Criteria) this;
    }

    public Criteria andClientOsIsNull() {
      addCriterion("ol.client_os is null");
      return (Criteria) this;
    }

    public Criteria andClientOsIsNotNull() {
      addCriterion("ol.client_os is not null");
      return (Criteria) this;
    }

    public Criteria andClientOsEqualTo(String value) {
      addCriterion("ol.client_os =", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsNotEqualTo(String value) {
      addCriterion("ol.client_os <>", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsGreaterThan(String value) {
      addCriterion("ol.client_os >", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsGreaterThanOrEqualTo(String value) {
      addCriterion("ol.client_os >=", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsLessThan(String value) {
      addCriterion("ol.client_os <", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsLessThanOrEqualTo(String value) {
      addCriterion("ol.client_os <=", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsLike(String value) {
      addCriterion("ol.client_os like", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsNotLike(String value) {
      addCriterion("ol.client_os not like", value, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsIn(List<String> values) {
      addCriterion("ol.client_os in", values, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsNotIn(List<String> values) {
      addCriterion("ol.client_os not in", values, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsBetween(String value1, String value2) {
      addCriterion("ol.client_os between", value1, value2, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientOsNotBetween(String value1, String value2) {
      addCriterion("ol.client_os not between", value1, value2, "clientOs");
      return (Criteria) this;
    }

    public Criteria andClientBrowserIsNull() {
      addCriterion("ol.client_browser is null");
      return (Criteria) this;
    }

    public Criteria andClientBrowserIsNotNull() {
      addCriterion("ol.client_browser is not null");
      return (Criteria) this;
    }

    public Criteria andClientBrowserEqualTo(String value) {
      addCriterion("ol.client_browser =", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserNotEqualTo(String value) {
      addCriterion("ol.client_browser <>", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserGreaterThan(String value) {
      addCriterion("ol.client_browser >", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserGreaterThanOrEqualTo(String value) {
      addCriterion("ol.client_browser >=", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserLessThan(String value) {
      addCriterion("ol.client_browser <", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserLessThanOrEqualTo(String value) {
      addCriterion("ol.client_browser <=", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserLike(String value) {
      addCriterion("ol.client_browser like", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserNotLike(String value) {
      addCriterion("ol.client_browser not like", value, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserIn(List<String> values) {
      addCriterion("ol.client_browser in", values, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserNotIn(List<String> values) {
      addCriterion("ol.client_browser not in", values, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserBetween(String value1, String value2) {
      addCriterion("ol.client_browser between", value1, value2, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserNotBetween(String value1, String value2) {
      addCriterion("ol.client_browser not between", value1, value2, "clientBrowser");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionIsNull() {
      addCriterion("ol.client_browser_version is null");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionIsNotNull() {
      addCriterion("ol.client_browser_version is not null");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionEqualTo(String value) {
      addCriterion("ol.client_browser_version =", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionNotEqualTo(String value) {
      addCriterion("ol.client_browser_version <>", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionGreaterThan(String value) {
      addCriterion("ol.client_browser_version >", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionGreaterThanOrEqualTo(String value) {
      addCriterion("ol.client_browser_version >=", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionLessThan(String value) {
      addCriterion("ol.client_browser_version <", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionLessThanOrEqualTo(String value) {
      addCriterion("ol.client_browser_version <=", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionLike(String value) {
      addCriterion("ol.client_browser_version like", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionNotLike(String value) {
      addCriterion("ol.client_browser_version not like", value, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionIn(List<String> values) {
      addCriterion("ol.client_browser_version in", values, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionNotIn(List<String> values) {
      addCriterion("ol.client_browser_version not in", values, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionBetween(String value1, String value2) {
      addCriterion("ol.client_browser_version between", value1, value2, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andClientBrowserVersionNotBetween(String value1, String value2) {
      addCriterion("ol.client_browser_version not between", value1, value2, "clientBrowserVersion");
      return (Criteria) this;
    }

    public Criteria andUserUsernameIsNull() {
      addCriterion("u.username is null");
      return (Criteria) this;
    }

    public Criteria andUserUsernameIsNotNull() {
      addCriterion("u.username is not null");
      return (Criteria) this;
    }

    public Criteria andUserUsernameEqualTo(String value) {
      addCriterion("u.username =", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameNotEqualTo(String value) {
      addCriterion("u.username <>", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameGreaterThan(String value) {
      addCriterion("u.username >", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameGreaterThanOrEqualTo(String value) {
      addCriterion("u.username >=", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameLessThan(String value) {
      addCriterion("u.username <", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameLessThanOrEqualTo(String value) {
      addCriterion("u.username <=", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameLike(String value) {
      addCriterion("u.username like", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameNotLike(String value) {
      addCriterion("u.username not like", value, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameIn(List<String> values) {
      addCriterion("u.username in", values, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameNotIn(List<String> values) {
      addCriterion("u.username not in", values, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameBetween(String value1, String value2) {
      addCriterion("u.username between", value1, value2, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserUsernameNotBetween(String value1, String value2) {
      addCriterion("u.username not between", value1, value2, "userUsername");
      return (Criteria) this;
    }

    public Criteria andUserNicknameIsNull() {
      addCriterion("u.nickname is null");
      return (Criteria) this;
    }

    public Criteria andUserNicknameIsNotNull() {
      addCriterion("u.nickname is not null");
      return (Criteria) this;
    }

    public Criteria andUserNicknameEqualTo(String value) {
      addCriterion("u.nickname =", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameNotEqualTo(String value) {
      addCriterion("u.nickname <>", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameGreaterThan(String value) {
      addCriterion("u.nickname >", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameGreaterThanOrEqualTo(String value) {
      addCriterion("u.nickname >=", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameLessThan(String value) {
      addCriterion("u.nickname <", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameLessThanOrEqualTo(String value) {
      addCriterion("u.nickname <=", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameLike(String value) {
      addCriterion("u.nickname like", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameNotLike(String value) {
      addCriterion("u.nickname not like", value, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameIn(List<String> values) {
      addCriterion("u.nickname in", values, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameNotIn(List<String> values) {
      addCriterion("u.nickname not in", values, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameBetween(String value1, String value2) {
      addCriterion("u.nickname between", value1, value2, "userNickname");
      return (Criteria) this;
    }

    public Criteria andUserNicknameNotBetween(String value1, String value2) {
      addCriterion("u.nickname not between", value1, value2, "userNickname");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated do_not_delete_during_merge Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_operation_log
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}