package com.jez.modules.admin.system.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ResourceExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public ResourceExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("r.id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("r.id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("r.id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("r.id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("r.id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("r.id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("r.id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("r.id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("r.id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("r.id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("r.id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("r.id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNull() {
      addCriterion("r.created_by is null");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNotNull() {
      addCriterion("r.created_by is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedByEqualTo(Long value) {
      addCriterion("r.created_by =", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotEqualTo(Long value) {
      addCriterion("r.created_by <>", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThan(Long value) {
      addCriterion("r.created_by >", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
      addCriterion("r.created_by >=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThan(Long value) {
      addCriterion("r.created_by <", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThanOrEqualTo(Long value) {
      addCriterion("r.created_by <=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByIn(List<Long> values) {
      addCriterion("r.created_by in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotIn(List<Long> values) {
      addCriterion("r.created_by not in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByBetween(Long value1, Long value2) {
      addCriterion("r.created_by between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotBetween(Long value1, Long value2) {
      addCriterion("r.created_by not between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNull() {
      addCriterion("r.created_date is null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNotNull() {
      addCriterion("r.created_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateEqualTo(Date value) {
      addCriterion("r.created_date =", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotEqualTo(Date value) {
      addCriterion("r.created_date <>", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThan(Date value) {
      addCriterion("r.created_date >", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("r.created_date >=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThan(Date value) {
      addCriterion("r.created_date <", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
      addCriterion("r.created_date <=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIn(List<Date> values) {
      addCriterion("r.created_date in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotIn(List<Date> values) {
      addCriterion("r.created_date not in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateBetween(Date value1, Date value2) {
      addCriterion("r.created_date between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
      addCriterion("r.created_date not between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNull() {
      addCriterion("r.last_modified_by is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNotNull() {
      addCriterion("r.last_modified_by is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByEqualTo(Long value) {
      addCriterion("r.last_modified_by =", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotEqualTo(Long value) {
      addCriterion("r.last_modified_by <>", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThan(Long value) {
      addCriterion("r.last_modified_by >", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThanOrEqualTo(Long value) {
      addCriterion("r.last_modified_by >=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThan(Long value) {
      addCriterion("r.last_modified_by <", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThanOrEqualTo(Long value) {
      addCriterion("r.last_modified_by <=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIn(List<Long> values) {
      addCriterion("r.last_modified_by in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotIn(List<Long> values) {
      addCriterion("r.last_modified_by not in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByBetween(Long value1, Long value2) {
      addCriterion("r.last_modified_by between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotBetween(Long value1, Long value2) {
      addCriterion("r.last_modified_by not between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNull() {
      addCriterion("r.last_modified_date is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNotNull() {
      addCriterion("r.last_modified_date is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateEqualTo(Date value) {
      addCriterion("r.last_modified_date =", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotEqualTo(Date value) {
      addCriterion("r.last_modified_date <>", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThan(Date value) {
      addCriterion("r.last_modified_date >", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("r.last_modified_date >=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThan(Date value) {
      addCriterion("r.last_modified_date <", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
      addCriterion("r.last_modified_date <=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIn(List<Date> values) {
      addCriterion("r.last_modified_date in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotIn(List<Date> values) {
      addCriterion("r.last_modified_date not in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
      addCriterion("r.last_modified_date between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
      addCriterion("r.last_modified_date not between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andParentIdIsNull() {
      addCriterion("r.parent_id is null");
      return (Criteria) this;
    }

    public Criteria andParentIdIsNotNull() {
      addCriterion("r.parent_id is not null");
      return (Criteria) this;
    }

    public Criteria andParentIdEqualTo(Long value) {
      addCriterion("r.parent_id =", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdNotEqualTo(Long value) {
      addCriterion("r.parent_id <>", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdGreaterThan(Long value) {
      addCriterion("r.parent_id >", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
      addCriterion("r.parent_id >=", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdLessThan(Long value) {
      addCriterion("r.parent_id <", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdLessThanOrEqualTo(Long value) {
      addCriterion("r.parent_id <=", value, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdIn(List<Long> values) {
      addCriterion("r.parent_id in", values, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdNotIn(List<Long> values) {
      addCriterion("r.parent_id not in", values, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdBetween(Long value1, Long value2) {
      addCriterion("r.parent_id between", value1, value2, "parentId");
      return (Criteria) this;
    }

    public Criteria andParentIdNotBetween(Long value1, Long value2) {
      addCriterion("r.parent_id not between", value1, value2, "parentId");
      return (Criteria) this;
    }

    public Criteria andLftIsNull() {
      addCriterion("r.lft is null");
      return (Criteria) this;
    }

    public Criteria andLftIsNotNull() {
      addCriterion("r.lft is not null");
      return (Criteria) this;
    }

    public Criteria andLftEqualTo(Long value) {
      addCriterion("r.lft =", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftNotEqualTo(Long value) {
      addCriterion("r.lft <>", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftGreaterThan(Long value) {
      addCriterion("r.lft >", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftGreaterThanOrEqualTo(Long value) {
      addCriterion("r.lft >=", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftLessThan(Long value) {
      addCriterion("r.lft <", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftLessThanOrEqualTo(Long value) {
      addCriterion("r.lft <=", value, "lft");
      return (Criteria) this;
    }

    public Criteria andLftIn(List<Long> values) {
      addCriterion("r.lft in", values, "lft");
      return (Criteria) this;
    }

    public Criteria andLftNotIn(List<Long> values) {
      addCriterion("r.lft not in", values, "lft");
      return (Criteria) this;
    }

    public Criteria andLftBetween(Long value1, Long value2) {
      addCriterion("r.lft between", value1, value2, "lft");
      return (Criteria) this;
    }

    public Criteria andLftNotBetween(Long value1, Long value2) {
      addCriterion("r.lft not between", value1, value2, "lft");
      return (Criteria) this;
    }

    public Criteria andRtIsNull() {
      addCriterion("r.rt is null");
      return (Criteria) this;
    }

    public Criteria andRtIsNotNull() {
      addCriterion("r.rt is not null");
      return (Criteria) this;
    }

    public Criteria andRtEqualTo(Long value) {
      addCriterion("r.rt =", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtNotEqualTo(Long value) {
      addCriterion("r.rt <>", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtGreaterThan(Long value) {
      addCriterion("r.rt >", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtGreaterThanOrEqualTo(Long value) {
      addCriterion("r.rt >=", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtLessThan(Long value) {
      addCriterion("r.rt <", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtLessThanOrEqualTo(Long value) {
      addCriterion("r.rt <=", value, "rt");
      return (Criteria) this;
    }

    public Criteria andRtIn(List<Long> values) {
      addCriterion("r.rt in", values, "rt");
      return (Criteria) this;
    }

    public Criteria andRtNotIn(List<Long> values) {
      addCriterion("r.rt not in", values, "rt");
      return (Criteria) this;
    }

    public Criteria andRtBetween(Long value1, Long value2) {
      addCriterion("r.rt between", value1, value2, "rt");
      return (Criteria) this;
    }

    public Criteria andRtNotBetween(Long value1, Long value2) {
      addCriterion("r.rt not between", value1, value2, "rt");
      return (Criteria) this;
    }

    public Criteria andLevelIsNull() {
      addCriterion("r.level is null");
      return (Criteria) this;
    }

    public Criteria andLevelIsNotNull() {
      addCriterion("r.level is not null");
      return (Criteria) this;
    }

    public Criteria andLevelEqualTo(Integer value) {
      addCriterion("r.level =", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelNotEqualTo(Integer value) {
      addCriterion("r.level <>", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelGreaterThan(Integer value) {
      addCriterion("r.level >", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelGreaterThanOrEqualTo(Integer value) {
      addCriterion("r.level >=", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelLessThan(Integer value) {
      addCriterion("r.level <", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelLessThanOrEqualTo(Integer value) {
      addCriterion("r.level <=", value, "level");
      return (Criteria) this;
    }

    public Criteria andLevelIn(List<Integer> values) {
      addCriterion("r.level in", values, "level");
      return (Criteria) this;
    }

    public Criteria andLevelNotIn(List<Integer> values) {
      addCriterion("r.level not in", values, "level");
      return (Criteria) this;
    }

    public Criteria andLevelBetween(Integer value1, Integer value2) {
      addCriterion("r.level between", value1, value2, "level");
      return (Criteria) this;
    }

    public Criteria andLevelNotBetween(Integer value1, Integer value2) {
      addCriterion("r.level not between", value1, value2, "level");
      return (Criteria) this;
    }

    public Criteria andTypeIsNull() {
      addCriterion("r.type is null");
      return (Criteria) this;
    }

    public Criteria andTypeIsNotNull() {
      addCriterion("r.type is not null");
      return (Criteria) this;
    }

    public Criteria andTypeEqualTo(Integer value) {
      addCriterion("r.type =", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotEqualTo(Integer value) {
      addCriterion("r.type <>", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThan(Integer value) {
      addCriterion("r.type >", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
      addCriterion("r.type >=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThan(Integer value) {
      addCriterion("r.type <", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeLessThanOrEqualTo(Integer value) {
      addCriterion("r.type <=", value, "type");
      return (Criteria) this;
    }

    public Criteria andTypeIn(List<Integer> values) {
      addCriterion("r.type in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotIn(List<Integer> values) {
      addCriterion("r.type not in", values, "type");
      return (Criteria) this;
    }

    public Criteria andTypeBetween(Integer value1, Integer value2) {
      addCriterion("r.type between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andTypeNotBetween(Integer value1, Integer value2) {
      addCriterion("r.type not between", value1, value2, "type");
      return (Criteria) this;
    }

    public Criteria andNameIsNull() {
      addCriterion("r.name is null");
      return (Criteria) this;
    }

    public Criteria andNameIsNotNull() {
      addCriterion("r.name is not null");
      return (Criteria) this;
    }

    public Criteria andNameEqualTo(String value) {
      addCriterion("r.name =", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotEqualTo(String value) {
      addCriterion("r.name <>", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThan(String value) {
      addCriterion("r.name >", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameGreaterThanOrEqualTo(String value) {
      addCriterion("r.name >=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThan(String value) {
      addCriterion("r.name <", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLessThanOrEqualTo(String value) {
      addCriterion("r.name <=", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameLike(String value) {
      addCriterion("r.name like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotLike(String value) {
      addCriterion("r.name not like", value, "name");
      return (Criteria) this;
    }

    public Criteria andNameIn(List<String> values) {
      addCriterion("r.name in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotIn(List<String> values) {
      addCriterion("r.name not in", values, "name");
      return (Criteria) this;
    }

    public Criteria andNameBetween(String value1, String value2) {
      addCriterion("r.name between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andNameNotBetween(String value1, String value2) {
      addCriterion("r.name not between", value1, value2, "name");
      return (Criteria) this;
    }

    public Criteria andPermissionIsNull() {
      addCriterion("r.permission is null");
      return (Criteria) this;
    }

    public Criteria andPermissionIsNotNull() {
      addCriterion("r.permission is not null");
      return (Criteria) this;
    }

    public Criteria andPermissionEqualTo(String value) {
      addCriterion("r.permission =", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotEqualTo(String value) {
      addCriterion("r.permission <>", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionGreaterThan(String value) {
      addCriterion("r.permission >", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionGreaterThanOrEqualTo(String value) {
      addCriterion("r.permission >=", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionLessThan(String value) {
      addCriterion("r.permission <", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionLessThanOrEqualTo(String value) {
      addCriterion("r.permission <=", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionLike(String value) {
      addCriterion("r.permission like", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotLike(String value) {
      addCriterion("r.permission not like", value, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionIn(List<String> values) {
      addCriterion("r.permission in", values, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotIn(List<String> values) {
      addCriterion("r.permission not in", values, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionBetween(String value1, String value2) {
      addCriterion("r.permission between", value1, value2, "permission");
      return (Criteria) this;
    }

    public Criteria andPermissionNotBetween(String value1, String value2) {
      addCriterion("r.permission not between", value1, value2, "permission");
      return (Criteria) this;
    }

    public Criteria andPathExpIsNull() {
      addCriterion("r.path_exp is null");
      return (Criteria) this;
    }

    public Criteria andPathExpIsNotNull() {
      addCriterion("r.path_exp is not null");
      return (Criteria) this;
    }

    public Criteria andPathExpEqualTo(String value) {
      addCriterion("r.path_exp =", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpNotEqualTo(String value) {
      addCriterion("r.path_exp <>", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpGreaterThan(String value) {
      addCriterion("r.path_exp >", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpGreaterThanOrEqualTo(String value) {
      addCriterion("r.path_exp >=", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpLessThan(String value) {
      addCriterion("r.path_exp <", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpLessThanOrEqualTo(String value) {
      addCriterion("r.path_exp <=", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpLike(String value) {
      addCriterion("r.path_exp like", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpNotLike(String value) {
      addCriterion("r.path_exp not like", value, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpIn(List<String> values) {
      addCriterion("r.path_exp in", values, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpNotIn(List<String> values) {
      addCriterion("r.path_exp not in", values, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpBetween(String value1, String value2) {
      addCriterion("r.path_exp between", value1, value2, "pathExp");
      return (Criteria) this;
    }

    public Criteria andPathExpNotBetween(String value1, String value2) {
      addCriterion("r.path_exp not between", value1, value2, "pathExp");
      return (Criteria) this;
    }

    public Criteria andMethodIsNull() {
      addCriterion("r.method is null");
      return (Criteria) this;
    }

    public Criteria andMethodIsNotNull() {
      addCriterion("r.method is not null");
      return (Criteria) this;
    }

    public Criteria andMethodEqualTo(String value) {
      addCriterion("r.method =", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotEqualTo(String value) {
      addCriterion("r.method <>", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodGreaterThan(String value) {
      addCriterion("r.method >", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodGreaterThanOrEqualTo(String value) {
      addCriterion("r.method >=", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodLessThan(String value) {
      addCriterion("r.method <", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodLessThanOrEqualTo(String value) {
      addCriterion("r.method <=", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodLike(String value) {
      addCriterion("r.method like", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotLike(String value) {
      addCriterion("r.method not like", value, "method");
      return (Criteria) this;
    }

    public Criteria andMethodIn(List<String> values) {
      addCriterion("r.method in", values, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotIn(List<String> values) {
      addCriterion("r.method not in", values, "method");
      return (Criteria) this;
    }

    public Criteria andMethodBetween(String value1, String value2) {
      addCriterion("r.method between", value1, value2, "method");
      return (Criteria) this;
    }

    public Criteria andMethodNotBetween(String value1, String value2) {
      addCriterion("r.method not between", value1, value2, "method");
      return (Criteria) this;
    }

    public Criteria andIconIsNull() {
      addCriterion("r.icon is null");
      return (Criteria) this;
    }

    public Criteria andIconIsNotNull() {
      addCriterion("r.icon is not null");
      return (Criteria) this;
    }

    public Criteria andIconEqualTo(String value) {
      addCriterion("r.icon =", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconNotEqualTo(String value) {
      addCriterion("r.icon <>", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconGreaterThan(String value) {
      addCriterion("r.icon >", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconGreaterThanOrEqualTo(String value) {
      addCriterion("r.icon >=", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconLessThan(String value) {
      addCriterion("r.icon <", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconLessThanOrEqualTo(String value) {
      addCriterion("r.icon <=", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconLike(String value) {
      addCriterion("r.icon like", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconNotLike(String value) {
      addCriterion("r.icon not like", value, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconIn(List<String> values) {
      addCriterion("r.icon in", values, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconNotIn(List<String> values) {
      addCriterion("r.icon not in", values, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconBetween(String value1, String value2) {
      addCriterion("r.icon between", value1, value2, "Icon");
      return (Criteria) this;
    }

    public Criteria andIconNotBetween(String value1, String value2) {
      addCriterion("r.icon not between", value1, value2, "Icon");
      return (Criteria) this;
    }

    public Criteria andStatusIsNull() {
      addCriterion("r.status is null");
      return (Criteria) this;
    }

    public Criteria andStatusIsNotNull() {
      addCriterion("r.status is not null");
      return (Criteria) this;
    }

    public Criteria andStatusEqualTo(Integer value) {
      addCriterion("r.status =", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotEqualTo(Integer value) {
      addCriterion("r.status <>", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThan(Integer value) {
      addCriterion("r.status >", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
      addCriterion("r.status >=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThan(Integer value) {
      addCriterion("r.status <", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThanOrEqualTo(Integer value) {
      addCriterion("r.status <=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusIn(List<Integer> values) {
      addCriterion("r.status in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotIn(List<Integer> values) {
      addCriterion("r.status not in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusBetween(Integer value1, Integer value2) {
      addCriterion("r.status between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotBetween(Integer value1, Integer value2) {
      addCriterion("r.status not between", value1, value2, "status");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_resource
   *
   * @mbg.generated do_not_delete_during_merge Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_resource
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}