package com.jez.modules.admin.system.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  protected String orderByClause;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  protected boolean distinct;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public UserExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  protected abstract static class GeneratedCriteria {

    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("u.id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("u.id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Long value) {
      addCriterion("u.id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Long value) {
      addCriterion("u.id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Long value) {
      addCriterion("u.id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Long value) {
      addCriterion("u.id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Long value) {
      addCriterion("u.id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Long value) {
      addCriterion("u.id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Long> values) {
      addCriterion("u.id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Long> values) {
      addCriterion("u.id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Long value1, Long value2) {
      addCriterion("u.id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Long value1, Long value2) {
      addCriterion("u.id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNull() {
      addCriterion("u.created_by is null");
      return (Criteria) this;
    }

    public Criteria andCreatedByIsNotNull() {
      addCriterion("u.created_by is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedByEqualTo(Long value) {
      addCriterion("u.created_by =", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotEqualTo(Long value) {
      addCriterion("u.created_by <>", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThan(Long value) {
      addCriterion("u.created_by >", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
      addCriterion("u.created_by >=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThan(Long value) {
      addCriterion("u.created_by <", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByLessThanOrEqualTo(Long value) {
      addCriterion("u.created_by <=", value, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByIn(List<Long> values) {
      addCriterion("u.created_by in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotIn(List<Long> values) {
      addCriterion("u.created_by not in", values, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByBetween(Long value1, Long value2) {
      addCriterion("u.created_by between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedByNotBetween(Long value1, Long value2) {
      addCriterion("u.created_by not between", value1, value2, "createdBy");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNull() {
      addCriterion("u.created_date is null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIsNotNull() {
      addCriterion("u.created_date is not null");
      return (Criteria) this;
    }

    public Criteria andCreatedDateEqualTo(Date value) {
      addCriterion("u.created_date =", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotEqualTo(Date value) {
      addCriterion("u.created_date <>", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThan(Date value) {
      addCriterion("u.created_date >", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("u.created_date >=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThan(Date value) {
      addCriterion("u.created_date <", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
      addCriterion("u.created_date <=", value, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateIn(List<Date> values) {
      addCriterion("u.created_date in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotIn(List<Date> values) {
      addCriterion("u.created_date not in", values, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateBetween(Date value1, Date value2) {
      addCriterion("u.created_date between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
      addCriterion("u.created_date not between", value1, value2, "createdDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNull() {
      addCriterion("u.last_modified_by is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIsNotNull() {
      addCriterion("u.last_modified_by is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByEqualTo(Long value) {
      addCriterion("u.last_modified_by =", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotEqualTo(Long value) {
      addCriterion("u.last_modified_by <>", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThan(Long value) {
      addCriterion("u.last_modified_by >", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByGreaterThanOrEqualTo(Long value) {
      addCriterion("u.last_modified_by >=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThan(Long value) {
      addCriterion("u.last_modified_by <", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByLessThanOrEqualTo(Long value) {
      addCriterion("u.last_modified_by <=", value, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByIn(List<Long> values) {
      addCriterion("u.last_modified_by in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotIn(List<Long> values) {
      addCriterion("u.last_modified_by not in", values, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByBetween(Long value1, Long value2) {
      addCriterion("u.last_modified_by between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedByNotBetween(Long value1, Long value2) {
      addCriterion("u.last_modified_by not between", value1, value2, "lastModifiedBy");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNull() {
      addCriterion("u.last_modified_date is null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIsNotNull() {
      addCriterion("u.last_modified_date is not null");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateEqualTo(Date value) {
      addCriterion("u.last_modified_date =", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotEqualTo(Date value) {
      addCriterion("u.last_modified_date <>", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThan(Date value) {
      addCriterion("u.last_modified_date >", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateGreaterThanOrEqualTo(Date value) {
      addCriterion("u.last_modified_date >=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThan(Date value) {
      addCriterion("u.last_modified_date <", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateLessThanOrEqualTo(Date value) {
      addCriterion("u.last_modified_date <=", value, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateIn(List<Date> values) {
      addCriterion("u.last_modified_date in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotIn(List<Date> values) {
      addCriterion("u.last_modified_date not in", values, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateBetween(Date value1, Date value2) {
      addCriterion("u.last_modified_date between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andLastModifiedDateNotBetween(Date value1, Date value2) {
      addCriterion("u.last_modified_date not between", value1, value2, "lastModifiedDate");
      return (Criteria) this;
    }

    public Criteria andOfficeIdIsNull() {
      addCriterion("u.office_id is null");
      return (Criteria) this;
    }

    public Criteria andOfficeIdIsNotNull() {
      addCriterion("u.office_id is not null");
      return (Criteria) this;
    }

    public Criteria andOfficeIdEqualTo(Long value) {
      addCriterion("u.office_id =", value, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdNotEqualTo(Long value) {
      addCriterion("u.office_id <>", value, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdGreaterThan(Long value) {
      addCriterion("u.office_id >", value, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdGreaterThanOrEqualTo(Long value) {
      addCriterion("u.office_id >=", value, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdLessThan(Long value) {
      addCriterion("u.office_id <", value, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdLessThanOrEqualTo(Long value) {
      addCriterion("u.office_id <=", value, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdIn(List<Long> values) {
      addCriterion("u.office_id in", values, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdNotIn(List<Long> values) {
      addCriterion("u.office_id not in", values, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdBetween(Long value1, Long value2) {
      addCriterion("u.office_id between", value1, value2, "officeId");
      return (Criteria) this;
    }

    public Criteria andOfficeIdNotBetween(Long value1, Long value2) {
      addCriterion("u.office_id not between", value1, value2, "officeId");
      return (Criteria) this;
    }

    public Criteria andUsernameIsNull() {
      addCriterion("u.username is null");
      return (Criteria) this;
    }

    public Criteria andUsernameIsNotNull() {
      addCriterion("u.username is not null");
      return (Criteria) this;
    }

    public Criteria andUsernameEqualTo(String value) {
      addCriterion("u.username =", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameNotEqualTo(String value) {
      addCriterion("u.username <>", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameGreaterThan(String value) {
      addCriterion("u.username >", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameGreaterThanOrEqualTo(String value) {
      addCriterion("u.username >=", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameLessThan(String value) {
      addCriterion("u.username <", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameLessThanOrEqualTo(String value) {
      addCriterion("u.username <=", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameLike(String value) {
      addCriterion("u.username like", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameNotLike(String value) {
      addCriterion("u.username not like", value, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameIn(List<String> values) {
      addCriterion("u.username in", values, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameNotIn(List<String> values) {
      addCriterion("u.username not in", values, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameBetween(String value1, String value2) {
      addCriterion("u.username between", value1, value2, "username");
      return (Criteria) this;
    }

    public Criteria andUsernameNotBetween(String value1, String value2) {
      addCriterion("u.username not between", value1, value2, "username");
      return (Criteria) this;
    }

    public Criteria andPasswordIsNull() {
      addCriterion("u.password is null");
      return (Criteria) this;
    }

    public Criteria andPasswordIsNotNull() {
      addCriterion("u.password is not null");
      return (Criteria) this;
    }

    public Criteria andPasswordEqualTo(String value) {
      addCriterion("u.password =", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotEqualTo(String value) {
      addCriterion("u.password <>", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordGreaterThan(String value) {
      addCriterion("u.password >", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordGreaterThanOrEqualTo(String value) {
      addCriterion("u.password >=", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordLessThan(String value) {
      addCriterion("u.password <", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordLessThanOrEqualTo(String value) {
      addCriterion("u.password <=", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordLike(String value) {
      addCriterion("u.password like", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotLike(String value) {
      addCriterion("u.password not like", value, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordIn(List<String> values) {
      addCriterion("u.password in", values, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotIn(List<String> values) {
      addCriterion("u.password not in", values, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordBetween(String value1, String value2) {
      addCriterion("u.password between", value1, value2, "password");
      return (Criteria) this;
    }

    public Criteria andPasswordNotBetween(String value1, String value2) {
      addCriterion("u.password not between", value1, value2, "password");
      return (Criteria) this;
    }

    public Criteria andStatusIsNull() {
      addCriterion("u.status is null");
      return (Criteria) this;
    }

    public Criteria andStatusIsNotNull() {
      addCriterion("u.status is not null");
      return (Criteria) this;
    }

    public Criteria andStatusEqualTo(Integer value) {
      addCriterion("u.status =", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotEqualTo(Integer value) {
      addCriterion("u.status <>", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThan(Integer value) {
      addCriterion("u.status >", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
      addCriterion("u.status >=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThan(Integer value) {
      addCriterion("u.status <", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusLessThanOrEqualTo(Integer value) {
      addCriterion("u.status <=", value, "status");
      return (Criteria) this;
    }

    public Criteria andStatusIn(List<Integer> values) {
      addCriterion("u.status in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotIn(List<Integer> values) {
      addCriterion("u.status not in", values, "status");
      return (Criteria) this;
    }

    public Criteria andStatusBetween(Integer value1, Integer value2) {
      addCriterion("u.status between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andStatusNotBetween(Integer value1, Integer value2) {
      addCriterion("u.status not between", value1, value2, "status");
      return (Criteria) this;
    }

    public Criteria andNicknameIsNull() {
      addCriterion("u.nickname is null");
      return (Criteria) this;
    }

    public Criteria andNicknameIsNotNull() {
      addCriterion("u.nickname is not null");
      return (Criteria) this;
    }

    public Criteria andNicknameEqualTo(String value) {
      addCriterion("u.nickname =", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotEqualTo(String value) {
      addCriterion("u.nickname <>", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameGreaterThan(String value) {
      addCriterion("u.nickname >", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameGreaterThanOrEqualTo(String value) {
      addCriterion("u.nickname >=", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameLessThan(String value) {
      addCriterion("u.nickname <", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameLessThanOrEqualTo(String value) {
      addCriterion("u.nickname <=", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameLike(String value) {
      addCriterion("u.nickname like", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotLike(String value) {
      addCriterion("u.nickname not like", value, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameIn(List<String> values) {
      addCriterion("u.nickname in", values, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotIn(List<String> values) {
      addCriterion("u.nickname not in", values, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameBetween(String value1, String value2) {
      addCriterion("u.nickname between", value1, value2, "nickname");
      return (Criteria) this;
    }

    public Criteria andNicknameNotBetween(String value1, String value2) {
      addCriterion("u.nickname not between", value1, value2, "nickname");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberIsNull() {
      addCriterion("u.employee_number is null");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberIsNotNull() {
      addCriterion("u.employee_number is not null");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberEqualTo(String value) {
      addCriterion("u.employee_number =", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberNotEqualTo(String value) {
      addCriterion("u.employee_number <>", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberGreaterThan(String value) {
      addCriterion("u.employee_number >", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberGreaterThanOrEqualTo(String value) {
      addCriterion("u.employee_number >=", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberLessThan(String value) {
      addCriterion("u.employee_number <", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberLessThanOrEqualTo(String value) {
      addCriterion("u.employee_number <=", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberLike(String value) {
      addCriterion("u.employee_number like", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberNotLike(String value) {
      addCriterion("u.employee_number not like", value, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberIn(List<String> values) {
      addCriterion("u.employee_number in", values, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberNotIn(List<String> values) {
      addCriterion("u.employee_number not in", values, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberBetween(String value1, String value2) {
      addCriterion("u.employee_number between", value1, value2, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andEmployeeNumberNotBetween(String value1, String value2) {
      addCriterion("u.employee_number not between", value1, value2, "employeeNumber");
      return (Criteria) this;
    }

    public Criteria andRealNameIsNull() {
      addCriterion("u.real_name is null");
      return (Criteria) this;
    }

    public Criteria andRealNameIsNotNull() {
      addCriterion("u.real_name is not null");
      return (Criteria) this;
    }

    public Criteria andRealNameEqualTo(String value) {
      addCriterion("u.real_name =", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameNotEqualTo(String value) {
      addCriterion("u.real_name <>", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameGreaterThan(String value) {
      addCriterion("u.real_name >", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameGreaterThanOrEqualTo(String value) {
      addCriterion("u.real_name >=", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameLessThan(String value) {
      addCriterion("u.real_name <", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameLessThanOrEqualTo(String value) {
      addCriterion("u.real_name <=", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameLike(String value) {
      addCriterion("u.real_name like", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameNotLike(String value) {
      addCriterion("u.real_name not like", value, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameIn(List<String> values) {
      addCriterion("u.real_name in", values, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameNotIn(List<String> values) {
      addCriterion("u.real_name not in", values, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameBetween(String value1, String value2) {
      addCriterion("u.real_name between", value1, value2, "realName");
      return (Criteria) this;
    }

    public Criteria andRealNameNotBetween(String value1, String value2) {
      addCriterion("u.real_name not between", value1, value2, "realName");
      return (Criteria) this;
    }

    public Criteria andIdCardIsNull() {
      addCriterion("u.id_card is null");
      return (Criteria) this;
    }

    public Criteria andIdCardIsNotNull() {
      addCriterion("u.id_card is not null");
      return (Criteria) this;
    }

    public Criteria andIdCardEqualTo(String value) {
      addCriterion("u.id_card =", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotEqualTo(String value) {
      addCriterion("u.id_card <>", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardGreaterThan(String value) {
      addCriterion("u.id_card >", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardGreaterThanOrEqualTo(String value) {
      addCriterion("u.id_card >=", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLessThan(String value) {
      addCriterion("u.id_card <", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLessThanOrEqualTo(String value) {
      addCriterion("u.id_card <=", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardLike(String value) {
      addCriterion("u.id_card like", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotLike(String value) {
      addCriterion("u.id_card not like", value, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardIn(List<String> values) {
      addCriterion("u.id_card in", values, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotIn(List<String> values) {
      addCriterion("u.id_card not in", values, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardBetween(String value1, String value2) {
      addCriterion("u.id_card between", value1, value2, "idCard");
      return (Criteria) this;
    }

    public Criteria andIdCardNotBetween(String value1, String value2) {
      addCriterion("u.id_card not between", value1, value2, "idCard");
      return (Criteria) this;
    }

    public Criteria andSexIsNull() {
      addCriterion("u.sex is null");
      return (Criteria) this;
    }

    public Criteria andSexIsNotNull() {
      addCriterion("u.sex is not null");
      return (Criteria) this;
    }

    public Criteria andSexEqualTo(Integer value) {
      addCriterion("u.sex =", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotEqualTo(Integer value) {
      addCriterion("u.sex <>", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexGreaterThan(Integer value) {
      addCriterion("u.sex >", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexGreaterThanOrEqualTo(Integer value) {
      addCriterion("u.sex >=", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexLessThan(Integer value) {
      addCriterion("u.sex <", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexLessThanOrEqualTo(Integer value) {
      addCriterion("u.sex <=", value, "sex");
      return (Criteria) this;
    }

    public Criteria andSexIn(List<Integer> values) {
      addCriterion("u.sex in", values, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotIn(List<Integer> values) {
      addCriterion("u.sex not in", values, "sex");
      return (Criteria) this;
    }

    public Criteria andSexBetween(Integer value1, Integer value2) {
      addCriterion("u.sex between", value1, value2, "sex");
      return (Criteria) this;
    }

    public Criteria andSexNotBetween(Integer value1, Integer value2) {
      addCriterion("u.sex not between", value1, value2, "sex");
      return (Criteria) this;
    }

    public Criteria andBirthdayIsNull() {
      addCriterion("u.birthday is null");
      return (Criteria) this;
    }

    public Criteria andBirthdayIsNotNull() {
      addCriterion("u.birthday is not null");
      return (Criteria) this;
    }

    public Criteria andBirthdayEqualTo(Date value) {
      addCriterion("u.birthday =", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayNotEqualTo(Date value) {
      addCriterion("u.birthday <>", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayGreaterThan(Date value) {
      addCriterion("u.birthday >", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
      addCriterion("u.birthday >=", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayLessThan(Date value) {
      addCriterion("u.birthday <", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayLessThanOrEqualTo(Date value) {
      addCriterion("u.birthday <=", value, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayIn(List<Date> values) {
      addCriterion("u.birthday in", values, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayNotIn(List<Date> values) {
      addCriterion("u.birthday not in", values, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayBetween(Date value1, Date value2) {
      addCriterion("u.birthday between", value1, value2, "birthday");
      return (Criteria) this;
    }

    public Criteria andBirthdayNotBetween(Date value1, Date value2) {
      addCriterion("u.birthday not between", value1, value2, "birthday");
      return (Criteria) this;
    }

    public Criteria andTelephoneIsNull() {
      addCriterion("u.telephone is null");
      return (Criteria) this;
    }

    public Criteria andTelephoneIsNotNull() {
      addCriterion("u.telephone is not null");
      return (Criteria) this;
    }

    public Criteria andTelephoneEqualTo(String value) {
      addCriterion("u.telephone =", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotEqualTo(String value) {
      addCriterion("u.telephone <>", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneGreaterThan(String value) {
      addCriterion("u.telephone >", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
      addCriterion("u.telephone >=", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneLessThan(String value) {
      addCriterion("u.telephone <", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneLessThanOrEqualTo(String value) {
      addCriterion("u.telephone <=", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneLike(String value) {
      addCriterion("u.telephone like", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotLike(String value) {
      addCriterion("u.telephone not like", value, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneIn(List<String> values) {
      addCriterion("u.telephone in", values, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotIn(List<String> values) {
      addCriterion("u.telephone not in", values, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneBetween(String value1, String value2) {
      addCriterion("u.telephone between", value1, value2, "telephone");
      return (Criteria) this;
    }

    public Criteria andTelephoneNotBetween(String value1, String value2) {
      addCriterion("u.telephone not between", value1, value2, "telephone");
      return (Criteria) this;
    }

    public Criteria andCellphoneIsNull() {
      addCriterion("u.cellphone is null");
      return (Criteria) this;
    }

    public Criteria andCellphoneIsNotNull() {
      addCriterion("u.cellphone is not null");
      return (Criteria) this;
    }

    public Criteria andCellphoneEqualTo(String value) {
      addCriterion("u.cellphone =", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneNotEqualTo(String value) {
      addCriterion("u.cellphone <>", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneGreaterThan(String value) {
      addCriterion("u.cellphone >", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneGreaterThanOrEqualTo(String value) {
      addCriterion("u.cellphone >=", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneLessThan(String value) {
      addCriterion("u.cellphone <", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneLessThanOrEqualTo(String value) {
      addCriterion("u.cellphone <=", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneLike(String value) {
      addCriterion("u.cellphone like", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneNotLike(String value) {
      addCriterion("u.cellphone not like", value, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneIn(List<String> values) {
      addCriterion("u.cellphone in", values, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneNotIn(List<String> values) {
      addCriterion("u.cellphone not in", values, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneBetween(String value1, String value2) {
      addCriterion("u.cellphone between", value1, value2, "cellphone");
      return (Criteria) this;
    }

    public Criteria andCellphoneNotBetween(String value1, String value2) {
      addCriterion("u.cellphone not between", value1, value2, "cellphone");
      return (Criteria) this;
    }

    public Criteria andEmailIsNull() {
      addCriterion("u.email is null");
      return (Criteria) this;
    }

    public Criteria andEmailIsNotNull() {
      addCriterion("u.email is not null");
      return (Criteria) this;
    }

    public Criteria andEmailEqualTo(String value) {
      addCriterion("u.email =", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotEqualTo(String value) {
      addCriterion("u.email <>", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailGreaterThan(String value) {
      addCriterion("u.email >", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailGreaterThanOrEqualTo(String value) {
      addCriterion("u.email >=", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLessThan(String value) {
      addCriterion("u.email <", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLessThanOrEqualTo(String value) {
      addCriterion("u.email <=", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailLike(String value) {
      addCriterion("u.email like", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotLike(String value) {
      addCriterion("u.email not like", value, "email");
      return (Criteria) this;
    }

    public Criteria andEmailIn(List<String> values) {
      addCriterion("u.email in", values, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotIn(List<String> values) {
      addCriterion("u.email not in", values, "email");
      return (Criteria) this;
    }

    public Criteria andEmailBetween(String value1, String value2) {
      addCriterion("u.email between", value1, value2, "email");
      return (Criteria) this;
    }

    public Criteria andEmailNotBetween(String value1, String value2) {
      addCriterion("u.email not between", value1, value2, "email");
      return (Criteria) this;
    }

    public Criteria andAddressIsNull() {
      addCriterion("u.address is null");
      return (Criteria) this;
    }

    public Criteria andAddressIsNotNull() {
      addCriterion("u.address is not null");
      return (Criteria) this;
    }

    public Criteria andAddressEqualTo(String value) {
      addCriterion("u.address =", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotEqualTo(String value) {
      addCriterion("u.address <>", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressGreaterThan(String value) {
      addCriterion("u.address >", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressGreaterThanOrEqualTo(String value) {
      addCriterion("u.address >=", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLessThan(String value) {
      addCriterion("u.address <", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLessThanOrEqualTo(String value) {
      addCriterion("u.address <=", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressLike(String value) {
      addCriterion("u.address like", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotLike(String value) {
      addCriterion("u.address not like", value, "address");
      return (Criteria) this;
    }

    public Criteria andAddressIn(List<String> values) {
      addCriterion("u.address in", values, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotIn(List<String> values) {
      addCriterion("u.address not in", values, "address");
      return (Criteria) this;
    }

    public Criteria andAddressBetween(String value1, String value2) {
      addCriterion("u.address between", value1, value2, "address");
      return (Criteria) this;
    }

    public Criteria andAddressNotBetween(String value1, String value2) {
      addCriterion("u.address not between", value1, value2, "address");
      return (Criteria) this;
    }

    public Criteria andAddressDetailIsNull() {
      addCriterion("u.address_detail is null");
      return (Criteria) this;
    }

    public Criteria andAddressDetailIsNotNull() {
      addCriterion("u.address_detail is not null");
      return (Criteria) this;
    }

    public Criteria andAddressDetailEqualTo(String value) {
      addCriterion("u.address_detail =", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotEqualTo(String value) {
      addCriterion("u.address_detail <>", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailGreaterThan(String value) {
      addCriterion("u.address_detail >", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailGreaterThanOrEqualTo(String value) {
      addCriterion("u.address_detail >=", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailLessThan(String value) {
      addCriterion("u.address_detail <", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailLessThanOrEqualTo(String value) {
      addCriterion("u.address_detail <=", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailLike(String value) {
      addCriterion("u.address_detail like", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotLike(String value) {
      addCriterion("u.address_detail not like", value, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailIn(List<String> values) {
      addCriterion("u.address_detail in", values, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotIn(List<String> values) {
      addCriterion("u.address_detail not in", values, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailBetween(String value1, String value2) {
      addCriterion("u.address_detail between", value1, value2, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andAddressDetailNotBetween(String value1, String value2) {
      addCriterion("u.address_detail not between", value1, value2, "addressDetail");
      return (Criteria) this;
    }

    public Criteria andZipCodeIsNull() {
      addCriterion("u.zip_code is null");
      return (Criteria) this;
    }

    public Criteria andZipCodeIsNotNull() {
      addCriterion("u.zip_code is not null");
      return (Criteria) this;
    }

    public Criteria andZipCodeEqualTo(String value) {
      addCriterion("u.zip_code =", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotEqualTo(String value) {
      addCriterion("u.zip_code <>", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeGreaterThan(String value) {
      addCriterion("u.zip_code >", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeGreaterThanOrEqualTo(String value) {
      addCriterion("u.zip_code >=", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeLessThan(String value) {
      addCriterion("u.zip_code <", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeLessThanOrEqualTo(String value) {
      addCriterion("u.zip_code <=", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeLike(String value) {
      addCriterion("u.zip_code like", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotLike(String value) {
      addCriterion("u.zip_code not like", value, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeIn(List<String> values) {
      addCriterion("u.zip_code in", values, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotIn(List<String> values) {
      addCriterion("u.zip_code not in", values, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeBetween(String value1, String value2) {
      addCriterion("u.zip_code between", value1, value2, "zipCode");
      return (Criteria) this;
    }

    public Criteria andZipCodeNotBetween(String value1, String value2) {
      addCriterion("u.zip_code not between", value1, value2, "zipCode");
      return (Criteria) this;
    }

    public Criteria andNativeAddressIsNull() {
      addCriterion("u.native_address is null");
      return (Criteria) this;
    }

    public Criteria andNativeAddressIsNotNull() {
      addCriterion("u.native_address is not null");
      return (Criteria) this;
    }

    public Criteria andNativeAddressEqualTo(String value) {
      addCriterion("u.native_address =", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressNotEqualTo(String value) {
      addCriterion("u.native_address <>", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressGreaterThan(String value) {
      addCriterion("u.native_address >", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressGreaterThanOrEqualTo(String value) {
      addCriterion("u.native_address >=", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressLessThan(String value) {
      addCriterion("u.native_address <", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressLessThanOrEqualTo(String value) {
      addCriterion("u.native_address <=", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressLike(String value) {
      addCriterion("u.native_address like", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressNotLike(String value) {
      addCriterion("u.native_address not like", value, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressIn(List<String> values) {
      addCriterion("u.native_address in", values, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressNotIn(List<String> values) {
      addCriterion("u.native_address not in", values, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressBetween(String value1, String value2) {
      addCriterion("u.native_address between", value1, value2, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andNativeAddressNotBetween(String value1, String value2) {
      addCriterion("u.native_address not between", value1, value2, "nativeAddress");
      return (Criteria) this;
    }

    public Criteria andBloodTypeIsNull() {
      addCriterion("u.blood_type is null");
      return (Criteria) this;
    }

    public Criteria andBloodTypeIsNotNull() {
      addCriterion("u.blood_type is not null");
      return (Criteria) this;
    }

    public Criteria andBloodTypeEqualTo(Integer value) {
      addCriterion("u.blood_type =", value, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeNotEqualTo(Integer value) {
      addCriterion("u.blood_type <>", value, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeGreaterThan(Integer value) {
      addCriterion("u.blood_type >", value, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeGreaterThanOrEqualTo(Integer value) {
      addCriterion("u.blood_type >=", value, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeLessThan(Integer value) {
      addCriterion("u.blood_type <", value, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeLessThanOrEqualTo(Integer value) {
      addCriterion("u.blood_type <=", value, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeIn(List<Integer> values) {
      addCriterion("u.blood_type in", values, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeNotIn(List<Integer> values) {
      addCriterion("u.blood_type not in", values, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeBetween(Integer value1, Integer value2) {
      addCriterion("u.blood_type between", value1, value2, "bloodType");
      return (Criteria) this;
    }

    public Criteria andBloodTypeNotBetween(Integer value1, Integer value2) {
      addCriterion("u.blood_type not between", value1, value2, "bloodType");
      return (Criteria) this;
    }

    public Criteria andSchoolIsNull() {
      addCriterion("u.school is null");
      return (Criteria) this;
    }

    public Criteria andSchoolIsNotNull() {
      addCriterion("u.school is not null");
      return (Criteria) this;
    }

    public Criteria andSchoolEqualTo(String value) {
      addCriterion("u.school =", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolNotEqualTo(String value) {
      addCriterion("u.school <>", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolGreaterThan(String value) {
      addCriterion("u.school >", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolGreaterThanOrEqualTo(String value) {
      addCriterion("u.school >=", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolLessThan(String value) {
      addCriterion("u.school <", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolLessThanOrEqualTo(String value) {
      addCriterion("u.school <=", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolLike(String value) {
      addCriterion("u.school like", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolNotLike(String value) {
      addCriterion("u.school not like", value, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolIn(List<String> values) {
      addCriterion("u.school in", values, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolNotIn(List<String> values) {
      addCriterion("u.school not in", values, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolBetween(String value1, String value2) {
      addCriterion("u.school between", value1, value2, "school");
      return (Criteria) this;
    }

    public Criteria andSchoolNotBetween(String value1, String value2) {
      addCriterion("u.school not between", value1, value2, "school");
      return (Criteria) this;
    }

    public Criteria andDegreeIsNull() {
      addCriterion("u.degree is null");
      return (Criteria) this;
    }

    public Criteria andDegreeIsNotNull() {
      addCriterion("u.degree is not null");
      return (Criteria) this;
    }

    public Criteria andDegreeEqualTo(String value) {
      addCriterion("u.degree =", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeNotEqualTo(String value) {
      addCriterion("u.degree <>", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeGreaterThan(String value) {
      addCriterion("u.degree >", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeGreaterThanOrEqualTo(String value) {
      addCriterion("u.degree >=", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeLessThan(String value) {
      addCriterion("u.degree <", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeLessThanOrEqualTo(String value) {
      addCriterion("u.degree <=", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeLike(String value) {
      addCriterion("u.degree like", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeNotLike(String value) {
      addCriterion("u.degree not like", value, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeIn(List<String> values) {
      addCriterion("u.degree in", values, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeNotIn(List<String> values) {
      addCriterion("u.degree not in", values, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeBetween(String value1, String value2) {
      addCriterion("u.degree between", value1, value2, "degree");
      return (Criteria) this;
    }

    public Criteria andDegreeNotBetween(String value1, String value2) {
      addCriterion("u.degree not between", value1, value2, "degree");
      return (Criteria) this;
    }

    public Criteria andMajorIsNull() {
      addCriterion("u.major is null");
      return (Criteria) this;
    }

    public Criteria andMajorIsNotNull() {
      addCriterion("u.major is not null");
      return (Criteria) this;
    }

    public Criteria andMajorEqualTo(String value) {
      addCriterion("u.major =", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorNotEqualTo(String value) {
      addCriterion("u.major <>", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorGreaterThan(String value) {
      addCriterion("u.major >", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorGreaterThanOrEqualTo(String value) {
      addCriterion("u.major >=", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorLessThan(String value) {
      addCriterion("u.major <", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorLessThanOrEqualTo(String value) {
      addCriterion("u.major <=", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorLike(String value) {
      addCriterion("u.major like", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorNotLike(String value) {
      addCriterion("u.major not like", value, "major");
      return (Criteria) this;
    }

    public Criteria andMajorIn(List<String> values) {
      addCriterion("u.major in", values, "major");
      return (Criteria) this;
    }

    public Criteria andMajorNotIn(List<String> values) {
      addCriterion("u.major not in", values, "major");
      return (Criteria) this;
    }

    public Criteria andMajorBetween(String value1, String value2) {
      addCriterion("u.major between", value1, value2, "major");
      return (Criteria) this;
    }

    public Criteria andMajorNotBetween(String value1, String value2) {
      addCriterion("u.major not between", value1, value2, "major");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_user
   *
   * @mbg.generated do_not_delete_during_merge Fri Sep 01 14:35:01 CST 2017
   */
  public static class Criteria extends GeneratedCriteria {

    protected Criteria() {
      super();
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table
   * sys_user
   *
   * @mbg.generated Fri Sep 01 14:35:01 CST 2017
   */
  public static class Criterion {

    private String condition;

    private Object value;

    private Object secondValue;

    private boolean noValue;

    private boolean singleValue;

    private boolean betweenValue;

    private boolean listValue;

    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }
}