package com.jez.modules.admin.system.entity;

import com.jez.core.persistence.entity.Auditable;
import com.jez.core.validation.groups.Create;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

public class Dict implements Auditable<Long, Long> {

  private static final long serialVersionUID = -5598137119001898516L;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.id
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.created_by
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long createdBy;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.created_date
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Date createdDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.last_modified_by
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long lastModifiedBy;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.last_modified_date
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Date lastModifiedDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.type
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @NotNull(groups = Create.class)
  @Length(min = 1, max = 100)
  private String type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.value
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @NotNull(groups = Create.class)
  @Length(min = 1, max = 100)
  private String value;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.label
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @NotNull(groups = Create.class)
  @Length(min = 1, max = 100)
  private String label;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.sort
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long sort;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_dict.remarks
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @Length(max = 255)
  private String remarks;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.id
   *
   * @return the value of sys_dict.id
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.id
   *
   * @param id the value for sys_dict.id
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.created_by
   *
   * @return the value of sys_dict.created_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getCreatedBy() {
    return createdBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.created_by
   *
   * @param createdBy the value for sys_dict.created_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.created_date
   *
   * @return the value of sys_dict.created_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Date getCreatedDate() {
    return createdDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.created_date
   *
   * @param createdDate the value for sys_dict.created_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.last_modified_by
   *
   * @return the value of sys_dict.last_modified_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getLastModifiedBy() {
    return lastModifiedBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.last_modified_by
   *
   * @param lastModifiedBy the value for sys_dict.last_modified_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLastModifiedBy(Long lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.last_modified_date
   *
   * @return the value of sys_dict.last_modified_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Date getLastModifiedDate() {
    return lastModifiedDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.last_modified_date
   *
   * @param lastModifiedDate the value for sys_dict.last_modified_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLastModifiedDate(Date lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.type
   *
   * @return the value of sys_dict.type
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.type
   *
   * @param type the value for sys_dict.type
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setType(String type) {
    this.type = type == null ? null : type.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.value
   *
   * @return the value of sys_dict.value
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getValue() {
    return value;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.value
   *
   * @param value the value for sys_dict.value
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setValue(String value) {
    this.value = value == null ? null : value.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.label
   *
   * @return the value of sys_dict.label
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getLabel() {
    return label;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.label
   *
   * @param label the value for sys_dict.label
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLabel(String label) {
    this.label = label == null ? null : label.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.sort
   *
   * @return the value of sys_dict.sort
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getSort() {
    return sort;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.sort
   *
   * @param sort the value for sys_dict.sort
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setSort(Long sort) {
    this.sort = sort;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_dict.remarks
   *
   * @return the value of sys_dict.remarks
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getRemarks() {
    return remarks;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_dict.remarks
   *
   * @param remarks the value for sys_dict.remarks
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setRemarks(String remarks) {
    this.remarks = remarks == null ? null : remarks.trim();
  }
}