package com.jez.modules.admin.system.entity;

import com.jez.core.persistence.entity.Persistable;
import java.util.Date;

public class OperationLog implements Persistable<Long> {

  /**
   *
   */
  private static final long serialVersionUID = -22144791000925115L;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.id
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.user_id
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private Long userId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.operate_time
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private Date operateTime;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.title
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String title;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.server_path
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String serverPath;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.servlet_path
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String servletPath;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.method
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String method;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.response_status
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private Integer responseStatus;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.response_millis
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private Long responseMillis;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.client_ip
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String clientIp;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.client_device
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String clientDevice;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.client_os
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String clientOs;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.client_browser
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String clientBrowser;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.client_browser_version
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String clientBrowserVersion;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.headers
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String headers;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.parameters
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String parameters;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_operation_log.payload
   *
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  private String payload;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.id
   *
   * @return the value of sys_operation_log.id
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.id
   *
   * @param id the value for sys_operation_log.id
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.user_id
   *
   * @return the value of sys_operation_log.user_id
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Long getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.user_id
   *
   * @param userId the value for sys_operation_log.user_id
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setUserId(Long userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.operate_time
   *
   * @return the value of sys_operation_log.operate_time
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Date getOperateTime() {
    return operateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.operate_time
   *
   * @param operateTime the value for sys_operation_log.operate_time
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setOperateTime(Date operateTime) {
    this.operateTime = operateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.title
   *
   * @return the value of sys_operation_log.title
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getTitle() {
    return title;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.title
   *
   * @param title the value for sys_operation_log.title
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.server_path
   *
   * @return the value of sys_operation_log.server_path
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getServerPath() {
    return serverPath;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.server_path
   *
   * @param serverPath the value for sys_operation_log.server_path
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setServerPath(String serverPath) {
    this.serverPath = serverPath == null ? null : serverPath.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.servlet_path
   *
   * @return the value of sys_operation_log.servlet_path
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getServletPath() {
    return servletPath;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.servlet_path
   *
   * @param servletPath the value for sys_operation_log.servlet_path
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setServletPath(String servletPath) {
    this.servletPath = servletPath == null ? null : servletPath.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.method
   *
   * @return the value of sys_operation_log.method
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getMethod() {
    return method;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.method
   *
   * @param method the value for sys_operation_log.method
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setMethod(String method) {
    this.method = method == null ? null : method.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.response_status
   *
   * @return the value of sys_operation_log.response_status
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Integer getResponseStatus() {
    return responseStatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.response_status
   *
   * @param responseStatus the value for sys_operation_log.response_status
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setResponseStatus(Integer responseStatus) {
    this.responseStatus = responseStatus;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.response_millis
   *
   * @return the value of sys_operation_log.response_millis
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public Long getResponseMillis() {
    return responseMillis;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.response_millis
   *
   * @param responseMillis the value for sys_operation_log.response_millis
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setResponseMillis(Long responseMillis) {
    this.responseMillis = responseMillis;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.client_ip
   *
   * @return the value of sys_operation_log.client_ip
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getClientIp() {
    return clientIp;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.client_ip
   *
   * @param clientIp the value for sys_operation_log.client_ip
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setClientIp(String clientIp) {
    this.clientIp = clientIp == null ? null : clientIp.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.client_device
   *
   * @return the value of sys_operation_log.client_device
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getClientDevice() {
    return clientDevice;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.client_device
   *
   * @param clientDevice the value for sys_operation_log.client_device
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setClientDevice(String clientDevice) {
    this.clientDevice = clientDevice == null ? null : clientDevice.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.client_os
   *
   * @return the value of sys_operation_log.client_os
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getClientOs() {
    return clientOs;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.client_os
   *
   * @param clientOs the value for sys_operation_log.client_os
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setClientOs(String clientOs) {
    this.clientOs = clientOs == null ? null : clientOs.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.client_browser
   *
   * @return the value of sys_operation_log.client_browser
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getClientBrowser() {
    return clientBrowser;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.client_browser
   *
   * @param clientBrowser the value for sys_operation_log.client_browser
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setClientBrowser(String clientBrowser) {
    this.clientBrowser = clientBrowser == null ? null : clientBrowser.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.client_browser_version
   *
   * @return the value of sys_operation_log.client_browser_version
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getClientBrowserVersion() {
    return clientBrowserVersion;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.client_browser_version
   *
   * @param clientBrowserVersion the value for sys_operation_log.client_browser_version
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setClientBrowserVersion(String clientBrowserVersion) {
    this.clientBrowserVersion = clientBrowserVersion == null ? null : clientBrowserVersion.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.headers
   *
   * @return the value of sys_operation_log.headers
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getHeaders() {
    return headers;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.headers
   *
   * @param headers the value for sys_operation_log.headers
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setHeaders(String headers) {
    this.headers = headers == null ? null : headers.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.parameters
   *
   * @return the value of sys_operation_log.parameters
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getParameters() {
    return parameters;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.parameters
   *
   * @param parameters the value for sys_operation_log.parameters
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setParameters(String parameters) {
    this.parameters = parameters == null ? null : parameters.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_operation_log.payload
   *
   * @return the value of sys_operation_log.payload
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public String getPayload() {
    return payload;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_operation_log.payload
   *
   * @param payload the value for sys_operation_log.payload
   * @mbg.generated Sun Jul 23 22:52:36 CST 2017
   */
  public void setPayload(String payload) {
    this.payload = payload == null ? null : payload.trim();
  }

  private String userUsername;

  private String userNickname;

  public String getUserUsername() {
    return userUsername;
  }

  public void setUserUsername(String userUsername) {
    this.userUsername = userUsername;
  }

  public String getUserNickname() {
    return userNickname;
  }

  public void setUserNickname(String userNickname) {
    this.userNickname = userNickname;
  }

}