package com.jez.modules.admin.system.entity;

import com.jez.core.persistence.entity.Auditable;
import com.jez.core.persistence.entity.NestedSet;
import com.jez.core.persistence.enums.EnableStatus;
import com.jez.core.validation.constraints.Enum;
import com.jez.core.validation.groups.Create;
import com.jez.modules.admin.system.enums.ResourceType;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.Length;

public class Resource implements Auditable<Long, Long>, NestedSet<Long> {

  private static final long serialVersionUID = -8946612701326170364L;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.id
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long id;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.created_by
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long createdBy;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.created_date
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Date createdDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.last_modified_by
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long lastModifiedBy;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.last_modified_date
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Date lastModifiedDate;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.parent_id
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long parentId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.lft
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long lft;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.rt
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Long rt;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.level
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  private Integer level;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.type
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @NotNull(groups = Create.class)
  @Enum(javaType = ResourceType.class, method = "getValue")
  private Integer type;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.name
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @NotNull(groups = Create.class)
  @Length(min = 1, max = 100)
  private String name;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.permission
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @Length(max = 50)
  private String permission;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.path_exp
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @Length(max = 255)
  private String pathExp;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.method
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @Length(max = 10)
  private String method;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.icon
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @Length(max = 255)
  private String icon;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * sys_resource.status
   *
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  @NotNull(groups = Create.class)
  @Enum(javaType = EnableStatus.class, method = "getValue")
  private Integer status;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.id
   *
   * @return the value of sys_resource.id
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.id
   *
   * @param id the value for sys_resource.id
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.created_by
   *
   * @return the value of sys_resource.created_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getCreatedBy() {
    return createdBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.created_by
   *
   * @param createdBy the value for sys_resource.created_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setCreatedBy(Long createdBy) {
    this.createdBy = createdBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.created_date
   *
   * @return the value of sys_resource.created_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Date getCreatedDate() {
    return createdDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.created_date
   *
   * @param createdDate the value for sys_resource.created_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setCreatedDate(Date createdDate) {
    this.createdDate = createdDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.last_modified_by
   *
   * @return the value of sys_resource.last_modified_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getLastModifiedBy() {
    return lastModifiedBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.last_modified_by
   *
   * @param lastModifiedBy the value for sys_resource.last_modified_by
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLastModifiedBy(Long lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.last_modified_date
   *
   * @return the value of sys_resource.last_modified_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Date getLastModifiedDate() {
    return lastModifiedDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.last_modified_date
   *
   * @param lastModifiedDate the value for sys_resource.last_modified_date
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLastModifiedDate(Date lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.parent_id
   *
   * @return the value of sys_resource.parent_id
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getParentId() {
    return parentId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.parent_id
   *
   * @param parentId the value for sys_resource.parent_id
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setParentId(Long parentId) {
    this.parentId = parentId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.lft
   *
   * @return the value of sys_resource.lft
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getLft() {
    return lft;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.lft
   *
   * @param lft the value for sys_resource.lft
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLft(Long lft) {
    this.lft = lft;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.rt
   *
   * @return the value of sys_resource.rt
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Long getRt() {
    return rt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.rt
   *
   * @param rt the value for sys_resource.rt
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setRt(Long rt) {
    this.rt = rt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.level
   *
   * @return the value of sys_resource.level
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Integer getLevel() {
    return level;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.level
   *
   * @param level the value for sys_resource.level
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setLevel(Integer level) {
    this.level = level;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.type
   *
   * @return the value of sys_resource.type
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Integer getType() {
    return type;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.type
   *
   * @param type the value for sys_resource.type
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setType(Integer type) {
    this.type = type;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.name
   *
   * @return the value of sys_resource.name
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.name
   *
   * @param name the value for sys_resource.name
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setName(String name) {
    this.name = name == null ? null : name.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.permission
   *
   * @return the value of sys_resource.permission
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getPermission() {
    return permission;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.permission
   *
   * @param permission the value for sys_resource.permission
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setPermission(String permission) {
    this.permission = permission == null ? null : permission.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.path_exp
   *
   * @return the value of sys_resource.path_exp
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getPathExp() {
    return pathExp;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.path_exp
   *
   * @param pathExp the value for sys_resource.path_exp
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setPathExp(String pathExp) {
    this.pathExp = pathExp == null ? null : pathExp.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.method
   *
   * @return the value of sys_resource.method
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getMethod() {
    return method;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.method
   *
   * @param method the value for sys_resource.method
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setMethod(String method) {
    this.method = method == null ? null : method.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.icon
   *
   * @return the value of sys_resource.icon
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public String getIcon() {
    return icon;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.icon
   *
   * @param icon the value for sys_resource.icon
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setIcon(String icon) {
    this.icon = icon == null ? null : icon.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column sys_resource.status
   *
   * @return the value of sys_resource.status
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public Integer getStatus() {
    return status;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column sys_resource.status
   *
   * @param status the value for sys_resource.status
   * @mbg.generated Mon Jun 19 16:26:28 CST 2017
   */
  public void setStatus(Integer status) {
    this.status = status;
  }
}